/* =========================================================================
   Métadonnées des sourates (Hafs ʿan ʿĀṣim, 6236 ayat).
   Chaque entrée : { n, ar, tr, ayahs }
   ========================================================================= */
window.HIFDH_META = [
  { n:  1, ar: "الفاتحة",   tr: "Al-Fātiḥa",     ayahs:   7 },
  { n:  2, ar: "البقرة",    tr: "Al-Baqara",     ayahs: 286 },
  { n:  3, ar: "آل عمران",  tr: "Āl ʿImrān",     ayahs: 200 },
  { n:  4, ar: "النساء",    tr: "An-Nisāʾ",      ayahs: 176 },
  { n:  5, ar: "المائدة",   tr: "Al-Māʾida",     ayahs: 120 },
  { n:  6, ar: "الأنعام",   tr: "Al-Anʿām",      ayahs: 165 },
  { n:  7, ar: "الأعراف",   tr: "Al-Aʿrāf",      ayahs: 206 },
  { n:  8, ar: "الأنفال",   tr: "Al-Anfāl",      ayahs:  75 },
  { n:  9, ar: "التوبة",    tr: "At-Tawba",      ayahs: 129 },
  { n: 10, ar: "يونس",      tr: "Yūnus",         ayahs: 109 },
  { n: 11, ar: "هود",       tr: "Hūd",           ayahs: 123 },
  { n: 12, ar: "يوسف",      tr: "Yūsuf",         ayahs: 111 },
  { n: 13, ar: "الرعد",     tr: "Ar-Raʿd",       ayahs:  43 },
  { n: 14, ar: "إبراهيم",   tr: "Ibrāhīm",       ayahs:  52 },
  { n: 15, ar: "الحجر",     tr: "Al-Ḥijr",       ayahs:  99 },
  { n: 16, ar: "النحل",     tr: "An-Naḥl",       ayahs: 128 },
  { n: 17, ar: "الإسراء",   tr: "Al-Isrāʾ",      ayahs: 111 },
  { n: 18, ar: "الكهف",     tr: "Al-Kahf",       ayahs: 110 },
  { n: 19, ar: "مريم",      tr: "Maryam",        ayahs:  98 },
  { n: 20, ar: "طه",        tr: "Ṭā-Hā",         ayahs: 135 },
  { n: 21, ar: "الأنبياء",  tr: "Al-Anbiyāʾ",    ayahs: 112 },
  { n: 22, ar: "الحج",      tr: "Al-Ḥajj",       ayahs:  78 },
  { n: 23, ar: "المؤمنون",  tr: "Al-Muʾminūn",   ayahs: 118 },
  { n: 24, ar: "النور",     tr: "An-Nūr",        ayahs:  64 },
  { n: 25, ar: "الفرقان",   tr: "Al-Furqān",     ayahs:  77 },
  { n: 26, ar: "الشعراء",   tr: "Ash-Shuʿarāʾ",  ayahs: 227 },
  { n: 27, ar: "النمل",     tr: "An-Naml",       ayahs:  93 },
  { n: 28, ar: "القصص",     tr: "Al-Qaṣaṣ",      ayahs:  88 },
  { n: 29, ar: "العنكبوت",  tr: "Al-ʿAnkabūt",   ayahs:  69 },
  { n: 30, ar: "الروم",     tr: "Ar-Rūm",        ayahs:  60 },
  { n: 31, ar: "لقمان",     tr: "Luqmān",        ayahs:  34 },
  { n: 32, ar: "السجدة",    tr: "As-Sajda",      ayahs:  30 },
  { n: 33, ar: "الأحزاب",   tr: "Al-Aḥzāb",      ayahs:  73 },
  { n: 34, ar: "سبأ",       tr: "Sabaʾ",         ayahs:  54 },
  { n: 35, ar: "فاطر",      tr: "Fāṭir",         ayahs:  45 },
  { n: 36, ar: "يس",        tr: "Yā-Sīn",        ayahs:  83 },
  { n: 37, ar: "الصافات",   tr: "Aṣ-Ṣāffāt",     ayahs: 182 },
  { n: 38, ar: "ص",         tr: "Ṣād",           ayahs:  88 },
  { n: 39, ar: "الزمر",     tr: "Az-Zumar",      ayahs:  75 },
  { n: 40, ar: "غافر",      tr: "Ghāfir",        ayahs:  85 },
  { n: 41, ar: "فصلت",      tr: "Fuṣṣilat",      ayahs:  54 },
  { n: 42, ar: "الشورى",    tr: "Ash-Shūrā",     ayahs:  53 },
  { n: 43, ar: "الزخرف",    tr: "Az-Zukhruf",    ayahs:  89 },
  { n: 44, ar: "الدخان",    tr: "Ad-Dukhān",     ayahs:  59 },
  { n: 45, ar: "الجاثية",   tr: "Al-Jāthiya",    ayahs:  37 },
  { n: 46, ar: "الأحقاف",   tr: "Al-Aḥqāf",      ayahs:  35 },
  { n: 47, ar: "محمد",      tr: "Muḥammad",      ayahs:  38 },
  { n: 48, ar: "الفتح",     tr: "Al-Fatḥ",       ayahs:  29 },
  { n: 49, ar: "الحجرات",   tr: "Al-Ḥujurāt",    ayahs:  18 },
  { n: 50, ar: "ق",         tr: "Qāf",           ayahs:  45 },
  { n: 51, ar: "الذاريات",  tr: "Adh-Dhāriyāt",  ayahs:  60 },
  { n: 52, ar: "الطور",     tr: "Aṭ-Ṭūr",        ayahs:  49 },
  { n: 53, ar: "النجم",     tr: "An-Najm",       ayahs:  62 },
  { n: 54, ar: "القمر",     tr: "Al-Qamar",      ayahs:  55 },
  { n: 55, ar: "الرحمن",    tr: "Ar-Raḥmān",     ayahs:  78 },
  { n: 56, ar: "الواقعة",   tr: "Al-Wāqiʿa",     ayahs:  96 },
  { n: 57, ar: "الحديد",    tr: "Al-Ḥadīd",      ayahs:  29 },
  { n: 58, ar: "المجادلة",  tr: "Al-Mujādala",   ayahs:  22 },
  { n: 59, ar: "الحشر",     tr: "Al-Ḥashr",      ayahs:  24 },
  { n: 60, ar: "الممتحنة",  tr: "Al-Mumtaḥana",  ayahs:  13 },
  { n: 61, ar: "الصف",      tr: "Aṣ-Ṣaff",       ayahs:  14 },
  { n: 62, ar: "الجمعة",    tr: "Al-Jumuʿa",     ayahs:  11 },
  { n: 63, ar: "المنافقون", tr: "Al-Munāfiqūn",  ayahs:  11 },
  { n: 64, ar: "التغابن",   tr: "At-Taghābun",   ayahs:  18 },
  { n: 65, ar: "الطلاق",    tr: "Aṭ-Ṭalāq",      ayahs:  12 },
  { n: 66, ar: "التحريم",   tr: "At-Taḥrīm",     ayahs:  12 },
  { n: 67, ar: "الملك",     tr: "Al-Mulk",       ayahs:  30 },
  { n: 68, ar: "القلم",     tr: "Al-Qalam",      ayahs:  52 },
  { n: 69, ar: "الحاقة",    tr: "Al-Ḥāqqa",      ayahs:  52 },
  { n: 70, ar: "المعارج",   tr: "Al-Maʿārij",    ayahs:  44 },
  { n: 71, ar: "نوح",       tr: "Nūḥ",           ayahs:  28 },
  { n: 72, ar: "الجن",      tr: "Al-Jinn",       ayahs:  28 },
  { n: 73, ar: "المزمل",    tr: "Al-Muzzammil",  ayahs:  20 },
  { n: 74, ar: "المدثر",    tr: "Al-Muddaththir",ayahs:  56 },
  { n: 75, ar: "القيامة",   tr: "Al-Qiyāma",     ayahs:  40 },
  { n: 76, ar: "الإنسان",   tr: "Al-Insān",      ayahs:  31 },
  { n: 77, ar: "المرسلات",  tr: "Al-Mursalāt",   ayahs:  50 },
  { n: 78, ar: "النبأ",     tr: "An-Nabaʾ",      ayahs:  40 },
  { n: 79, ar: "النازعات",  tr: "An-Nāziʿāt",    ayahs:  46 },
  { n: 80, ar: "عبس",       tr: "ʿAbasa",        ayahs:  42 },
  { n: 81, ar: "التكوير",   tr: "At-Takwīr",     ayahs:  29 },
  { n: 82, ar: "الانفطار",  tr: "Al-Infiṭār",    ayahs:  19 },
  { n: 83, ar: "المطففين",  tr: "Al-Muṭaffifīn", ayahs:  36 },
  { n: 84, ar: "الانشقاق",  tr: "Al-Inshiqāq",   ayahs:  25 },
  { n: 85, ar: "البروج",    tr: "Al-Burūj",      ayahs:  22 },
  { n: 86, ar: "الطارق",    tr: "Aṭ-Ṭāriq",      ayahs:  17 },
  { n: 87, ar: "الأعلى",    tr: "Al-Aʿlā",       ayahs:  19 },
  { n: 88, ar: "الغاشية",   tr: "Al-Ghāshiya",   ayahs:  26 },
  { n: 89, ar: "الفجر",     tr: "Al-Fajr",       ayahs:  30 },
  { n: 90, ar: "البلد",     tr: "Al-Balad",      ayahs:  20 },
  { n: 91, ar: "الشمس",     tr: "Ash-Shams",     ayahs:  15 },
  { n: 92, ar: "الليل",     tr: "Al-Layl",       ayahs:  21 },
  { n: 93, ar: "الضحى",     tr: "Aḍ-Ḍuḥā",       ayahs:  11 },
  { n: 94, ar: "الشرح",     tr: "Ash-Sharḥ",     ayahs:   8 },
  { n: 95, ar: "التين",     tr: "At-Tīn",        ayahs:   8 },
  { n: 96, ar: "العلق",     tr: "Al-ʿAlaq",      ayahs:  19 },
  { n: 97, ar: "القدر",     tr: "Al-Qadr",       ayahs:   5 },
  { n: 98, ar: "البينة",    tr: "Al-Bayyina",    ayahs:   8 },
  { n: 99, ar: "الزلزلة",   tr: "Az-Zalzala",    ayahs:   8 },
  { n:100, ar: "العاديات",  tr: "Al-ʿĀdiyāt",    ayahs:  11 },
  { n:101, ar: "القارعة",   tr: "Al-Qāriʿa",     ayahs:  11 },
  { n:102, ar: "التكاثر",   tr: "At-Takāthur",   ayahs:   8 },
  { n:103, ar: "العصر",     tr: "Al-ʿAṣr",       ayahs:   3 },
  { n:104, ar: "الهمزة",    tr: "Al-Humaza",     ayahs:   9 },
  { n:105, ar: "الفيل",     tr: "Al-Fīl",        ayahs:   5 },
  { n:106, ar: "قريش",      tr: "Quraysh",       ayahs:   4 },
  { n:107, ar: "الماعون",   tr: "Al-Māʿūn",      ayahs:   7 },
  { n:108, ar: "الكوثر",    tr: "Al-Kawthar",    ayahs:   3 },
  { n:109, ar: "الكافرون",  tr: "Al-Kāfirūn",    ayahs:   6 },
  { n:110, ar: "النصر",     tr: "An-Naṣr",       ayahs:   3 },
  { n:111, ar: "المسد",     tr: "Al-Masad",      ayahs:   5 },
  { n:112, ar: "الإخلاص",   tr: "Al-Ikhlāṣ",     ayahs:   4 },
  { n:113, ar: "الفلق",     tr: "Al-Falaq",      ayahs:   5 },
  { n:114, ar: "الناس",     tr: "An-Nās",        ayahs:   6 },
];
