/* =========================================================================
   RÉCITS DU CORAN — cartes de lecture (pas de quiz : on lit).
   Arabe simple (exercice de lecture) + traduction française sous chaque ligne.
   Chaque carte a au moins un verset. Chaque phrase a son analyse grammaticale
   (leçons 1–4), dépliable par un bouton.

   Adab : on ne met JAMAIS de paroles inventées dans la bouche d'Allah. Le
   récit RAPPORTE (« Allah annonce que… »). Seul le Coran est cité mot pour
   mot, et uniquement dans les panneaux de versets (window.VERSES).

   Carte : { ar:[lignes…], fr:[lignes…], refs:[clés], an:[analyseParLigne…] }
   Analyse d'une ligne : { words:[{w,type,role}…], takeaway }
     type ∈ nom | verbe | particule | pronom
   ========================================================================= */

window.STORIES = [
  {
    id: "isa",
    n: 1,
    title: "عِيسَى عَلَيْهِ السَّلَام",
    titleFr: "Le prophète ʿĪsā (Jésus)",
    subtitle: "De l'annonce à Marie jusqu'à l'élévation au ciel",
    cards: [
      {
        ar: ["كانَتْ مَرْيَمُ امْرَأَةً صالِحَةً طاهِرَةً.", "اِبْتَعَدَتْ عَنْ أَهْلِها إِلى مَكانٍ فِي الشَّرْقِ."],
        fr: ["Marie était une femme pieuse et pure.", "Elle s'éloigna de sa famille vers un lieu à l'est."],
        refs: ["19:16"],
        an: [
          { words: [
            { w: "كانَتْ", type: "verbe", role: "فعل ناسخ (« était »)" },
            { w: "مَرْيَمُ", type: "nom", role: "اسم كان — le sujet · cas رَفْع" },
            { w: "امْرَأَةً", type: "nom", role: "خبر كان · cas نَصْب (tanwin ـً)" },
            { w: "صالِحَةً", type: "nom", role: "نعت — adjectif · نَصْب" },
            { w: "طاهِرَةً", type: "nom", role: "نعت — adjectif · نَصْب" },
          ], takeaway: "كان rend son خبر au cas نصب ; les adjectifs (نعت) suivent le nom (leçon 4)." },
          { words: [
            { w: "اِبْتَعَدَتْ", type: "verbe", role: "فعل (« s'éloigna »)" },
            { w: "عَنْ", type: "particule", role: "حرف جر (« de »)" },
            { w: "أَهْلِ", type: "nom", role: "مجرور après عن · مضاف" },
            { w: "ـها", type: "pronom", role: "suffixe « sa » · مضاف إليه" },
            { w: "إِلى", type: "particule", role: "حرف جر (« vers »)" },
            { w: "مَكانٍ", type: "nom", role: "مجرور · نكرة (tanwin ـٍ)" },
            { w: "فِي", type: "particule", role: "حرف جر (« dans »)" },
            { w: "الشَّرْقِ", type: "nom", role: "مجرور · معرفة (الـ)" },
          ], takeaway: "Après chaque حرف جر, le nom passe au cas جرّ (kasra) — leçon 3." },
        ],
      },
      {
        ar: ["أَرْسَلَ اللَّهُ إِلَيْها المَلَكَ فِي صُورَةِ رَجُلٍ.", "أَخْبَرَها أَنَّهُ رَسُولٌ مِنْ رَبِّها لِيَهَبَ لَها وَلَدًا طاهِرًا."],
        fr: ["Allah lui envoya l'ange sous la forme d'un homme.", "Il l'informa qu'il était un messager de son Seigneur, pour lui accorder un fils pur."],
        refs: ["19:19"],
        an: [
          { words: [
            { w: "أَرْسَلَ", type: "verbe", role: "فعل (« envoya »)" },
            { w: "اللَّهُ", type: "nom", role: "فاعل — le sujet · رَفْع (ـُ)" },
            { w: "إِلَيْها", type: "particule", role: "إلى (حرف جر) + « elle »" },
            { w: "المَلَكَ", type: "nom", role: "مفعول به · نَصْب · معرفة" },
            { w: "فِي", type: "particule", role: "حرف جر" },
            { w: "صُورَةِ", type: "nom", role: "مجرور · مضاف" },
            { w: "رَجُلٍ", type: "nom", role: "مضاف إليه · نكرة" },
          ], takeaway: "فعل + فاعل + مفعول (leçons 1 & 3), avec l'إضافة صُورَةِ رَجُلٍ (leçon 2)." },
          { words: [
            { w: "أَخْبَرَ", type: "verbe", role: "فعل (« informa »)" },
            { w: "ـها", type: "pronom", role: "مفعول به (« la »)" },
            { w: "أَنَّهُ", type: "particule", role: "أنّ (« que ») + suffixe « il »" },
            { w: "رَسُولٌ", type: "nom", role: "خبر أنّ · نكرة (tanwin)" },
            { w: "مِنْ", type: "particule", role: "حرف جر" },
            { w: "رَبِّها", type: "nom", role: "مجرور · رَبّ + « son »" },
            { w: "لِيَهَبَ", type: "verbe", role: "لِـ + verbe (« pour donner »)" },
            { w: "لَها", type: "particule", role: "لِـ + « à elle »" },
            { w: "وَلَدًا", type: "nom", role: "مفعول به · نَصْب · نكرة" },
            { w: "طاهِرًا", type: "nom", role: "نعت — adjectif de ولد · نَصْب" },
          ], takeaway: "طاهِرًا est le نعت de وَلَدًا : même genre, indéfini, نصب (leçon 4)." },
        ],
      },
      {
        ar: ["بَشَّرَتْها المَلائِكَةُ بِكَلِمَةٍ مِنَ اللَّهِ.", "اسْمُهُ المَسِيحُ عِيسَى ابْنُ مَرْيَمَ."],
        fr: ["Les anges lui annoncèrent une parole venue d'Allah.", "Son nom est al-Masîḥ, ʿĪsā, fils de Marie."],
        refs: ["3:45"],
        an: [
          { words: [
            { w: "بَشَّرَتْ", type: "verbe", role: "فعل (« annoncèrent »)" },
            { w: "ـها", type: "pronom", role: "مفعول به (« lui »)" },
            { w: "المَلائِكَةُ", type: "nom", role: "فاعل · رَفْع · معرفة" },
            { w: "بِـ", type: "particule", role: "حرف جر (« de/par »)" },
            { w: "كَلِمَةٍ", type: "nom", role: "مجرور · نكرة (ـٍ)" },
            { w: "مِنَ", type: "particule", role: "حرف جر" },
            { w: "اللَّهِ", type: "nom", role: "مجرور · معرفة" },
          ], takeaway: "Sujet défini (المَلائِكَةُ, رفع) ; après بِـ et مِن, le nom est جرّ (leçon 3)." },
          { words: [
            { w: "اسْمُ", type: "nom", role: "مبتدأ — le sujet · مضاف" },
            { w: "ـهُ", type: "pronom", role: "« son » · مضاف إليه" },
            { w: "المَسِيحُ", type: "nom", role: "خبر — le prédicat · رَفْع · معرفة" },
            { w: "عِيسَى", type: "nom", role: "nom propre (apposé)" },
            { w: "ابْنُ", type: "nom", role: "nom · مضاف" },
            { w: "مَرْيَمَ", type: "nom", role: "مضاف إليه (diptote)" },
          ], takeaway: "Phrase nominale : اسْمُهُ (مبتدأ + suffixe) + المَسِيحُ (خبر) — leçons 2 & 4." },
        ],
      },
      {
        ar: ["تَعَجَّبَتْ مَرْيَمُ: كَيْفَ يَكُونُ لَها وَلَدٌ؟", "فَأَخْبَرَها المَلَكُ أَنَّ اللَّهَ يَخْلُقُ ما يَشاءُ بِأَمْرِهِ."],
        fr: ["Marie s'étonna : comment aurait-elle un enfant ?", "L'ange lui apprit qu'Allah crée ce qu'Il veut, par Son ordre."],
        refs: ["3:47"],
        an: [
          { words: [
            { w: "تَعَجَّبَتْ", type: "verbe", role: "فعل (« s'étonna »)" },
            { w: "مَرْيَمُ", type: "nom", role: "فاعل · رَفْع" },
            { w: "كَيْفَ", type: "nom", role: "mot interrogatif (« comment »)" },
            { w: "يَكُونُ", type: "verbe", role: "فعل (« être »)" },
            { w: "لَها", type: "particule", role: "لِـ + « à elle »" },
            { w: "وَلَدٌ", type: "nom", role: "اسم يكون · رَفْع · نكرة (ـٌ)" },
          ], takeaway: "وَلَدٌ est indéfini (tanwin ـٌ) : « un enfant » (leçon 1)." },
          { words: [
            { w: "فَـ", type: "particule", role: "حرف (« alors »)" },
            { w: "أَخْبَرَ", type: "verbe", role: "فعل" },
            { w: "ـها", type: "pronom", role: "مفعول به (« la »)" },
            { w: "المَلَكُ", type: "nom", role: "فاعل · رَفْع · معرفة" },
            { w: "أَنَّ", type: "particule", role: "حرف (« que »)" },
            { w: "اللَّهَ", type: "nom", role: "اسم أنّ · cas نَصْب (ـَ)" },
            { w: "يَخْلُقُ", type: "verbe", role: "فعل (« crée »)" },
            { w: "ما", type: "nom", role: "relatif (« ce que »)" },
            { w: "يَشاءُ", type: "verbe", role: "فعل (« Il veut »)" },
            { w: "بِأَمْرِ", type: "nom", role: "بِـ + أمر · مجرور · مضاف" },
            { w: "ـهِ", type: "pronom", role: "« Son » · مضاف إليه" },
          ], takeaway: "Après أنّ, le nom اللَّهَ passe au cas نصب (اسم أنّ) — leçon 3." },
        ],
      },
      {
        ar: ["حَمَلَتْ مَرْيَمُ بِعِيسَى بِإِذْنِ اللَّهِ.", "ثُمَّ اِبْتَعَدَتْ إِلى مَكانٍ بَعِيدٍ."],
        fr: ["Marie conçut ʿĪsā par la permission d'Allah.", "Puis elle se retira en un lieu éloigné."],
        refs: ["19:22"],
        an: [
          { words: [
            { w: "حَمَلَتْ", type: "verbe", role: "فعل (« conçut »)" },
            { w: "مَرْيَمُ", type: "nom", role: "فاعل · رَفْع" },
            { w: "بِعِيسَى", type: "nom", role: "بِـ + عيسى · مجرور" },
            { w: "بِإِذْنِ", type: "nom", role: "بِـ + إذن · مجرور · مضاف" },
            { w: "اللَّهِ", type: "nom", role: "مضاف إليه · جرّ" },
          ], takeaway: "إذْنِ اللَّهِ : une إضافة au cas جرّ après بِـ (leçons 2 & 3)." },
          { words: [
            { w: "ثُمَّ", type: "particule", role: "حرف عطف (« puis »)" },
            { w: "اِبْتَعَدَتْ", type: "verbe", role: "فعل (« se retira »)" },
            { w: "إِلى", type: "particule", role: "حرف جر" },
            { w: "مَكانٍ", type: "nom", role: "مجرور · نكرة (ـٍ)" },
            { w: "بَعِيدٍ", type: "nom", role: "نعت — adjectif de مكان · جرّ · نكرة" },
          ], takeaway: "بَعِيدٍ (adjectif) s'accorde avec مَكانٍ : indéfini + جرّ (leçon 4)." },
        ],
      },
      {
        ar: ["جاءَها المَخاضُ عِنْدَ جِذْعِ النَّخْلَةِ.", "تَمَنَّتْ لَوْ أَنَّها ماتَتْ قَبْلَ هٰذا اليَوْمِ."],
        fr: ["Les douleurs de l'enfantement la menèrent au tronc du palmier.", "Elle souhaita être morte avant ce jour."],
        refs: ["19:23"],
        an: [
          { words: [
            { w: "جاءَ", type: "verbe", role: "فعل (« vint »)" },
            { w: "ـها", type: "pronom", role: "مفعول به (« la »)" },
            { w: "المَخاضُ", type: "nom", role: "فاعل · رَفْع · معرفة (« les douleurs »)" },
            { w: "عِنْدَ", type: "nom", role: "ظرف مكان (« près de ») · نَصْب" },
            { w: "جِذْعِ", type: "nom", role: "مجرور · مضاف" },
            { w: "النَّخْلَةِ", type: "nom", role: "مضاف إليه · جرّ · معرفة" },
          ], takeaway: "جِذْعِ النَّخْلَةِ : une إضافة (« le tronc du palmier ») — leçon 2." },
          { words: [
            { w: "تَمَنَّتْ", type: "verbe", role: "فعل (« souhaita »)" },
            { w: "لَوْ", type: "particule", role: "حرف (« si »)" },
            { w: "أَنَّها", type: "particule", role: "أنّ + « elle »" },
            { w: "ماتَتْ", type: "verbe", role: "فعل (« mourut »)" },
            { w: "قَبْلَ", type: "nom", role: "ظرف زمان · نَصْب (« avant »)" },
            { w: "هٰذا", type: "nom", role: "اسم إشارة (« ce ») — leçon 2" },
            { w: "اليَوْمِ", type: "nom", role: "مجرور · معرفة (« le jour »)" },
          ], takeaway: "هٰذا = démonstratif (leçon 2) ; اليَوْمِ défini par الـ (leçon 1)." },
        ],
      },
      {
        ar: ["طَمْأَنَها صَوْتٌ مِنْ تَحْتِها.", "جَعَلَ اللَّهُ تَحْتَها نَهْرًا، وَأَمَرَها أَنْ تَهُزَّ النَّخْلَةَ لِيَسْقُطَ عَلَيْها الرُّطَبُ."],
        fr: ["Une voix, au-dessous d'elle, la rassura.", "Allah plaça sous elle un ruisseau, et lui ordonna de secouer le palmier pour que tombent sur elle les dattes fraîches."],
        refs: ["19:24", "19:25"],
        an: [
          { words: [
            { w: "طَمْأَنَ", type: "verbe", role: "فعل (« rassura »)" },
            { w: "ـها", type: "pronom", role: "مفعول به (« la »)" },
            { w: "صَوْتٌ", type: "nom", role: "فاعل · رَفْع · نكرة (ـٌ)" },
            { w: "مِنْ", type: "particule", role: "حرف جر" },
            { w: "تَحْتِ", type: "nom", role: "ظرف مكان · مجرور (« sous »)" },
            { w: "ـها", type: "pronom", role: "« elle » · مضاف إليه" },
          ], takeaway: "Le فاعل صَوْتٌ est indéfini (tanwin) : « une voix » (leçon 1)." },
          { words: [
            { w: "جَعَلَ", type: "verbe", role: "فعل (« plaça »)" },
            { w: "اللَّهُ", type: "nom", role: "فاعل · رَفْع" },
            { w: "تَحْتَها", type: "nom", role: "ظرف (« sous elle »)" },
            { w: "نَهْرًا", type: "nom", role: "مفعول به · نَصْب · نكرة" },
            { w: "وَ", type: "particule", role: "حرف عطف" },
            { w: "أَمَرَ", type: "verbe", role: "فعل (« ordonna »)" },
            { w: "ـها", type: "pronom", role: "مفعول به (« lui »)" },
            { w: "أَنْ", type: "particule", role: "حرف (« que »)" },
            { w: "تَهُزَّ", type: "verbe", role: "فعل (« secouer »)" },
            { w: "النَّخْلَةَ", type: "nom", role: "مفعول به · نَصْب · معرفة" },
          ], takeaway: "Deux verbes coordonnés par وَ ; chaque مفعول به est au cas نصب (leçon 3)." },
        ],
      },
      {
        ar: ["أَمَرَها اللَّهُ أَنْ تَصُومَ عَنِ الكَلامِ.", "ثُمَّ رَجَعَتْ إِلى قَوْمِها تَحْمِلُ طِفْلَها."],
        fr: ["Allah lui ordonna de s'abstenir de parler — un jeûne du silence.", "Puis elle revint vers son peuple en portant son enfant."],
        refs: ["19:26"],
        an: [
          { words: [
            { w: "أَمَرَ", type: "verbe", role: "فعل (« ordonna »)" },
            { w: "ـها", type: "pronom", role: "مفعول به (« lui »)" },
            { w: "اللَّهُ", type: "nom", role: "فاعل · رَفْع" },
            { w: "أَنْ", type: "particule", role: "حرف (« que »)" },
            { w: "تَصُومَ", type: "verbe", role: "فعل (« jeûner »)" },
            { w: "عَنِ", type: "particule", role: "حرف جر" },
            { w: "الكَلامِ", type: "nom", role: "مجرور · معرفة (« la parole »)" },
          ], takeaway: "Après عن, le nom الكَلامِ est au cas جرّ (kasra) — leçon 3." },
          { words: [
            { w: "ثُمَّ", type: "particule", role: "حرف عطف (« puis »)" },
            { w: "رَجَعَتْ", type: "verbe", role: "فعل (« revint »)" },
            { w: "إِلى", type: "particule", role: "حرف جر" },
            { w: "قَوْمِ", type: "nom", role: "مجرور · مضاف" },
            { w: "ـها", type: "pronom", role: "« son » · مضاف إليه" },
            { w: "تَحْمِلُ", type: "verbe", role: "فعل حال (« portant »)" },
            { w: "طِفْلَ", type: "nom", role: "مفعول به · نَصْب · مضاف" },
            { w: "ـها", type: "pronom", role: "« son » · مضاف إليه" },
          ], takeaway: "قَوْمِها et طِفْلَها : nom + pronom suffixe (إضافة) — leçons 2 & 4." },
        ],
      },
      {
        ar: ["تَعَجَّبَ القَوْمُ وَاتَّهَمُوا مَرْيَمَ.", "فَأَشارَتْ إِلى الطِّفْلِ لِيَسْأَلُوهُ."],
        fr: ["Le peuple s'étonna et accusa Marie.", "Elle désigna alors l'enfant pour qu'ils l'interrogent."],
        refs: ["19:29"],
        an: [
          { words: [
            { w: "تَعَجَّبَ", type: "verbe", role: "فعل (« s'étonna »)" },
            { w: "القَوْمُ", type: "nom", role: "فاعل · رَفْع · معرفة" },
            { w: "وَ", type: "particule", role: "حرف عطف" },
            { w: "اتَّهَمُوا", type: "verbe", role: "فعل (« accusèrent ») + و (pluriel)" },
            { w: "مَرْيَمَ", type: "nom", role: "مفعول به · نَصْب (diptote ـَ)" },
          ], takeaway: "مَرْيَمَ est مفعول به au cas نصب (leçon 3)." },
          { words: [
            { w: "فَـ", type: "particule", role: "حرف (« alors »)" },
            { w: "أَشارَتْ", type: "verbe", role: "فعل (« fit signe »)" },
            { w: "إِلى", type: "particule", role: "حرف جر" },
            { w: "الطِّفْلِ", type: "nom", role: "مجرور · معرفة (« l'enfant »)" },
            { w: "لِـ", type: "particule", role: "حرف (« pour »)" },
            { w: "يَسْأَلُو", type: "verbe", role: "فعل (« interroger »)" },
            { w: "ـهُ", type: "pronom", role: "مفعول به (« le »)" },
          ], takeaway: "Après إلى, الطِّفْلِ est au cas جرّ (leçon 3)." },
        ],
      },
      {
        ar: ["تَكَلَّمَ عِيسَى وَهُوَ طِفْلٌ فِي المَهْدِ.", "أَخْبَرَهُمْ أَنَّهُ عَبْدُ اللَّهِ، آتاهُ الكِتابَ وَجَعَلَهُ نَبِيًّا."],
        fr: ["ʿĪsā parla alors qu'il était un enfant au berceau.", "Il leur apprit qu'il est le serviteur d'Allah, qui lui a donné le Livre et a fait de lui un prophète."],
        refs: ["19:30"],
        an: [
          { words: [
            { w: "تَكَلَّمَ", type: "verbe", role: "فعل (« parla »)" },
            { w: "عِيسَى", type: "nom", role: "فاعل · رَفْع" },
            { w: "وَ", type: "particule", role: "واو الحال" },
            { w: "هُوَ", type: "pronom", role: "ضمير منفصل (« il ») · مبتدأ" },
            { w: "طِفْلٌ", type: "nom", role: "خبر · رَفْع · نكرة (ـٌ)" },
            { w: "فِي", type: "particule", role: "حرف جر" },
            { w: "المَهْدِ", type: "nom", role: "مجرور · معرفة" },
          ], takeaway: "هُوَ طِفْلٌ : petite phrase nominale (pronom + خبر indéfini) — leçons 2 & 4." },
          { words: [
            { w: "أَخْبَرَ", type: "verbe", role: "فعل" },
            { w: "ـهُمْ", type: "pronom", role: "مفعول به (« les »)" },
            { w: "أَنَّهُ", type: "particule", role: "أنّ + « il »" },
            { w: "عَبْدُ", type: "nom", role: "خبر أنّ · مضاف" },
            { w: "اللَّهِ", type: "nom", role: "مضاف إليه · جرّ" },
            { w: "آتاهُ", type: "verbe", role: "فعل + ـه (« lui donna »)" },
            { w: "الكِتابَ", type: "nom", role: "مفعول به · نَصْب · معرفة" },
            { w: "وَ", type: "particule", role: "حرف عطف" },
            { w: "جَعَلَهُ", type: "verbe", role: "فعل + ـه (« fit de lui »)" },
            { w: "نَبِيًّا", type: "nom", role: "مفعول به ثانٍ · نَصْب · نكرة" },
          ], takeaway: "عَبْدُ اللَّهِ : une إضافة, prédicat (خبر) de أنّ (leçon 2)." },
        ],
      },
      {
        ar: ["أَرْسَلَ اللَّهُ عِيسَى إِلى بَنِي إِسْرائِيلَ بِالمُعْجِزاتِ.", "كانَ يَخْلُقُ مِنَ الطِّينِ طَيْرًا، فَيَنْفُخُ فِيهِ فَيَصِيرُ حَيًّا بِإِذْنِ اللَّهِ."],
        fr: ["Allah envoya ʿĪsā aux enfants d'Israël avec des miracles.", "Il façonnait un oiseau dans l'argile, soufflait dedans, et il devenait vivant par la permission d'Allah."],
        refs: ["3:49"],
        an: [
          { words: [
            { w: "أَرْسَلَ", type: "verbe", role: "فعل (« envoya »)" },
            { w: "اللَّهُ", type: "nom", role: "فاعل · رَفْع (ـُ)" },
            { w: "عِيسَى", type: "nom", role: "مفعول به · نَصْب" },
            { w: "إِلى", type: "particule", role: "حرف جر" },
            { w: "بَنِي", type: "nom", role: "مجرور · مضاف" },
            { w: "إِسْرائِيلَ", type: "nom", role: "مضاف إليه" },
            { w: "بِالمُعْجِزاتِ", type: "nom", role: "بِـ + المعجزات · مجرور · معرفة" },
          ], takeaway: "Phrase verbale : فعل + فاعل + مفعول ; les 3 types (leçon 1) et les cas (leçon 3)." },
          { words: [
            { w: "كانَ", type: "verbe", role: "فعل ناسخ" },
            { w: "يَخْلُقُ", type: "verbe", role: "فعل (« façonnait »)" },
            { w: "مِنَ", type: "particule", role: "حرف جر" },
            { w: "الطِّينِ", type: "nom", role: "مجرور · معرفة (« l'argile »)" },
            { w: "طَيْرًا", type: "nom", role: "مفعول به · نَصْب · نكرة" },
            { w: "فَيَنْفُخُ", type: "verbe", role: "فَـ + verbe (« souffle »)" },
            { w: "فِيهِ", type: "particule", role: "في + « dedans »" },
            { w: "فَيَصِيرُ", type: "verbe", role: "فَـ + verbe (« devient »)" },
            { w: "حَيًّا", type: "nom", role: "خبر يصير · نَصْب · نكرة" },
            { w: "بِإِذْنِ", type: "nom", role: "بِـ + إذن · مضاف" },
            { w: "اللَّهِ", type: "nom", role: "مضاف إليه · جرّ" },
          ], takeaway: "بِإِذْنِ اللَّهِ : une إضافة au cas جرّ (leçons 2 & 3)." },
        ],
      },
      {
        ar: ["وَكانَ يَشْفِي الأَعْمى وَالأَبْرَصَ، وَيُحْيِي المَوْتى بِإِذْنِ اللَّهِ.", "وَيُخْبِرُ النّاسَ بِما يَأْكُلُونَ وَما يَدَّخِرُونَ فِي بُيُوتِهِمْ."],
        fr: ["Il guérissait l'aveugle-né et le lépreux, et ressuscitait les morts par la permission d'Allah.", "Et il informait les gens de ce qu'ils mangeaient et de ce qu'ils gardaient dans leurs maisons."],
        refs: ["5:110"],
        an: [
          { words: [
            { w: "وَكانَ", type: "verbe", role: "وَ + كان (ناسخ)" },
            { w: "يَشْفِي", type: "verbe", role: "فعل (« guérissait »)" },
            { w: "الأَعْمى", type: "nom", role: "مفعول به · معرفة (« l'aveugle »)" },
            { w: "وَالأَبْرَصَ", type: "nom", role: "معطوف · مفعول به · معرفة (« le lépreux »)" },
            { w: "وَيُحْيِي", type: "verbe", role: "وَ + verbe (« ressuscitait »)" },
            { w: "المَوْتى", type: "nom", role: "مفعول به · معرفة (« les morts »)" },
            { w: "بِإِذْنِ", type: "nom", role: "بِـ + إذن · مضاف" },
            { w: "اللَّهِ", type: "nom", role: "مضاف إليه · جرّ" },
          ], takeaway: "Objets définis par الـ (leçon 1) ; إضافة بِإِذْنِ اللَّهِ (leçon 2)." },
          { words: [
            { w: "وَيُخْبِرُ", type: "verbe", role: "وَ + verbe (« informait »)" },
            { w: "النّاسَ", type: "nom", role: "مفعول به · نَصْب · معرفة" },
            { w: "بِـ", type: "particule", role: "حرف جر" },
            { w: "ما", type: "nom", role: "relatif (« ce que »)" },
            { w: "يَأْكُلُونَ", type: "verbe", role: "فعل (« ils mangent ») + و" },
            { w: "فِي", type: "particule", role: "حرف جر" },
            { w: "بُيُوتِ", type: "nom", role: "مجرور · مضاف" },
            { w: "ـهِمْ", type: "pronom", role: "« leurs » · مضاف إليه" },
          ], takeaway: "بُيُوتِهِمْ : nom + suffixe pluriel ـهم (إضافة) — leçons 2 & 4." },
        ],
      },
      {
        ar: ["صَدَّقَ عِيسَى التَّوْراةَ الَّتِي قَبْلَهُ، وَجاءَ بِالإِنْجِيلِ.", "وَبَشَّرَ بِرَسُولٍ يَأْتِي بَعْدَهُ اسْمُهُ أَحْمَدُ."],
        fr: ["ʿĪsā confirma la Torah venue avant lui, et apporta l'Évangile.", "Et il annonça un messager qui viendrait après lui, nommé Aḥmad."],
        refs: ["3:50", "61:6"],
        an: [
          { words: [
            { w: "صَدَّقَ", type: "verbe", role: "فعل (« confirma »)" },
            { w: "عِيسَى", type: "nom", role: "فاعل · رَفْع" },
            { w: "التَّوْراةَ", type: "nom", role: "مفعول به · نَصْب · معرفة" },
            { w: "الَّتِي", type: "nom", role: "اسم موصول (« qui »)" },
            { w: "قَبْلَهُ", type: "nom", role: "ظرف (« avant lui »)" },
            { w: "وَجاءَ", type: "verbe", role: "وَ + verbe (« apporta »)" },
            { w: "بِالإِنْجِيلِ", type: "nom", role: "بِـ + الإنجيل · مجرور · معرفة" },
          ], takeaway: "التَّوْراةَ : مفعول به défini (الـ) au cas نصب (leçons 1 & 3)." },
          { words: [
            { w: "وَبَشَّرَ", type: "verbe", role: "وَ + verbe (« annonça »)" },
            { w: "بِرَسُولٍ", type: "nom", role: "بِـ + رسول · مجرور · نكرة (ـٍ)" },
            { w: "يَأْتِي", type: "verbe", role: "فعل (« viendra »)" },
            { w: "بَعْدَهُ", type: "nom", role: "ظرف (« après lui »)" },
            { w: "اسْمُ", type: "nom", role: "مبتدأ · مضاف" },
            { w: "ـهُ", type: "pronom", role: "« son » · مضاف إليه" },
            { w: "أَحْمَدُ", type: "nom", role: "خبر · رَفْع (diptote, sans tanwin)" },
          ], takeaway: "اسْمُهُ أَحْمَدُ : phrase nominale (مبتدأ + خبر) — leçon 2." },
        ],
      },
      {
        ar: ["آمَنَ بِهِ الحَوارِيُّونَ وَنَصَرُوهُ.", "طَلَبُوا مائِدَةً مِنَ السَّماءِ، فَدَعا عِيسى رَبَّهُ فَأَنْزَلَها اللَّهُ آيَةً لَهُمْ."],
        fr: ["Les disciples crurent en lui et le soutinrent.", "Ils demandèrent une table du ciel ; ʿĪsā invoqua son Seigneur, et Allah la fit descendre comme un signe pour eux."],
        refs: ["5:114"],
        an: [
          { words: [
            { w: "آمَنَ", type: "verbe", role: "فعل (« crurent »)" },
            { w: "بِهِ", type: "particule", role: "بِـ + « en lui »" },
            { w: "الحَوارِيُّونَ", type: "nom", role: "فاعل · رَفْع (pluriel sain ـُونَ) · معرفة" },
            { w: "وَنَصَرُو", type: "verbe", role: "وَ + verbe (« soutinrent »)" },
            { w: "ـهُ", type: "pronom", role: "مفعول به (« le »)" },
          ], takeaway: "الحَوارِيُّونَ : pluriel masculin sain (ـُونَ) au cas رفع — leçon 3." },
          { words: [
            { w: "طَلَبُوا", type: "verbe", role: "فعل (« demandèrent »)" },
            { w: "مائِدَةً", type: "nom", role: "مفعول به · نَصْب · نكرة (ـً)" },
            { w: "مِنَ", type: "particule", role: "حرف جر" },
            { w: "السَّماءِ", type: "nom", role: "مجرور · معرفة" },
            { w: "فَدَعا", type: "verbe", role: "فَـ + verbe (« invoqua »)" },
            { w: "عِيسى", type: "nom", role: "فاعل · رَفْع" },
            { w: "رَبَّ", type: "nom", role: "مفعول به · نَصْب · مضاف" },
            { w: "ـهُ", type: "pronom", role: "« son » · مضاف إليه" },
            { w: "فَأَنْزَلَها", type: "verbe", role: "فَـ + verbe + ـها (« la fit descendre »)" },
            { w: "اللَّهُ", type: "nom", role: "فاعل · رَفْع" },
            { w: "آيَةً", type: "nom", role: "حال / état · نَصْب · نكرة" },
          ], takeaway: "رَبَّهُ : nom + suffixe (إضافة), مفعول به au cas نصب (leçons 2, 3, 4)." },
        ],
      },
      {
        ar: ["أَرادَ الأَعْداءُ قَتْلَ عِيسى وَصَلْبَهُ.", "لٰكِنَّ اللَّهَ نَجّاهُ مِنْهُمْ."],
        fr: ["Les ennemis voulurent tuer ʿĪsā et le crucifier.", "Mais Allah le sauva d'eux."],
        refs: ["3:54"],
        an: [
          { words: [
            { w: "أَرادَ", type: "verbe", role: "فعل (« voulurent »)" },
            { w: "الأَعْداءُ", type: "nom", role: "فاعل · رَفْع · معرفة (الـ)" },
            { w: "قَتْلَ", type: "nom", role: "مفعول به · مضاف (sans الـ, sans tanwin)" },
            { w: "عِيسى", type: "nom", role: "مضاف إليه · جرّ" },
            { w: "وَصَلْبَ", type: "nom", role: "معطوف · مفعول به · مضاف" },
            { w: "ـهُ", type: "pronom", role: "« le » · مضاف إليه" },
          ], takeaway: "قَتْلَ عِيسى et صَلْبَهُ : deux إضافات (leçon 2) ; le فاعل est défini (leçon 1)." },
          { words: [
            { w: "لٰكِنَّ", type: "particule", role: "حرف ناسخ (« mais »)" },
            { w: "اللَّهَ", type: "nom", role: "اسم لٰكِنّ · cas نَصْب (ـَ)" },
            { w: "نَجّا", type: "verbe", role: "فعل (« sauva »)" },
            { w: "ـهُ", type: "pronom", role: "مفعول به (« le »)" },
            { w: "مِنْهُمْ", type: "particule", role: "مِن + « d'eux »" },
          ], takeaway: "Après لٰكِنَّ (sœur de إنّ), le nom اللَّهَ est منصوب — leçon 3." },
        ],
      },
      {
        ar: ["أَلْقى اللَّهُ شَبَهَ عِيسى عَلى رَجُلٍ آخَرَ.", "فَأَخَذَهُ الأَعْداءُ وَصَلَبُوهُ وَهُمْ يَحْسِبُونَهُ عِيسى."],
        fr: ["Allah projeta la ressemblance de ʿĪsā sur un autre homme.", "Les ennemis le saisirent et le crucifièrent, croyant que c'était ʿĪsā."],
        refs: ["4:157"],
        an: [
          { words: [
            { w: "أَلْقى", type: "verbe", role: "فعل (« projeta »)" },
            { w: "اللَّهُ", type: "nom", role: "فاعل · رَفْع" },
            { w: "شَبَهَ", type: "nom", role: "مفعول به · نَصْب · مضاف" },
            { w: "عِيسى", type: "nom", role: "مضاف إليه · جرّ" },
            { w: "عَلى", type: "particule", role: "حرف جر" },
            { w: "رَجُلٍ", type: "nom", role: "مجرور · نكرة (ـٍ)" },
            { w: "آخَرَ", type: "nom", role: "نعت — adjectif · جرّ (diptote, sans tanwin)" },
          ], takeaway: "شَبَهَ عِيسى : une إضافة ; آخَرَ est le نعت de رَجُلٍ (leçons 2 & 4)." },
          { words: [
            { w: "فَـ", type: "particule", role: "حرف عطف" },
            { w: "أَخَذَ", type: "verbe", role: "فعل (« saisirent »)" },
            { w: "ـهُ", type: "pronom", role: "مفعول به (« le »)" },
            { w: "الأَعْداءُ", type: "nom", role: "فاعل · رَفْع · معرفة" },
            { w: "وَصَلَبُو", type: "verbe", role: "وَ + verbe (« crucifièrent »)" },
            { w: "ـهُ", type: "pronom", role: "مفعول به (« le »)" },
            { w: "وَهُمْ", type: "pronom", role: "واو الحال + ضمير منفصل (« ils »)" },
            { w: "يَحْسِبُونَ", type: "verbe", role: "فعل (« croient »)" },
            { w: "ـهُ", type: "pronom", role: "مفعول به (« le »)" },
          ], takeaway: "هُمْ = pronom isolé, sujet d'une phrase d'état (حال) — leçon 4." },
        ],
      },
      {
        ar: ["فَما قَتَلُوا عِيسى وَما صَلَبُوهُ.", "بَلْ رَفَعَهُ اللَّهُ إِلَيْهِ إِلى السَّماءِ."],
        fr: ["Ils n'ont donc pas tué ʿĪsā ni ne l'ont crucifié.", "Allah l'éleva plutôt vers Lui, au ciel."],
        refs: ["4:158"],
        an: [
          { words: [
            { w: "فَـ", type: "particule", role: "حرف (« donc »)" },
            { w: "ما", type: "particule", role: "حرف نفي (« ne… pas »)" },
            { w: "قَتَلُوا", type: "verbe", role: "فعل (« tuèrent ») + و" },
            { w: "عِيسى", type: "nom", role: "مفعول به · نَصْب" },
            { w: "وَما", type: "particule", role: "وَ + ما (négation)" },
            { w: "صَلَبُو", type: "verbe", role: "فعل (« crucifièrent »)" },
            { w: "ـهُ", type: "pronom", role: "مفعول به (« le »)" },
          ], takeaway: "ما = particule de négation — un حرف (leçon 1)." },
          { words: [
            { w: "بَلْ", type: "particule", role: "حرف إضراب (« plutôt »)" },
            { w: "رَفَعَ", type: "verbe", role: "فعل (« éleva »)" },
            { w: "ـهُ", type: "pronom", role: "مفعول به (« le »)" },
            { w: "اللَّهُ", type: "nom", role: "فاعل · رَفْع" },
            { w: "إِلَيْهِ", type: "particule", role: "إلى + « vers Lui »" },
            { w: "إِلى", type: "particule", role: "حرف جر" },
            { w: "السَّماءِ", type: "nom", role: "مجرور · معرفة" },
          ], takeaway: "فعل + فاعل (اللَّهُ, رفع) + مفعول (ـه) — leçons 1 & 3." },
        ],
      },
      {
        ar: ["عِيسى عَبْدُ اللَّهِ وَرَسُولُهُ.", "وَهُوَ نَبِيٌّ كَرِيمٌ مِنْ أُولِي العَزْمِ."],
        fr: ["ʿĪsā est le serviteur d'Allah et Son messager.", "C'est un noble prophète, parmi ceux dotés de fermeté (ūlū al-ʿazm)."],
        refs: ["43:59"],
        an: [
          { words: [
            { w: "عِيسى", type: "nom", role: "مُبْتَدَأ — le sujet (nom propre, défini)" },
            { w: "عَبْدُ", type: "nom", role: "خَبَر — le prédicat · مضاف" },
            { w: "اللَّهِ", type: "nom", role: "مضاف إليه · جرّ (kasra)" },
            { w: "وَ", type: "particule", role: "حرف عطف (« et »)" },
            { w: "رَسُولُ", type: "nom", role: "coordonné au خبر · مضاف" },
            { w: "ـهُ", type: "pronom", role: "suffixe « son » · مضاف إليه" },
          ], takeaway: "Phrase nominale sans « être » : مبتدأ + خبر (leçon 2), deux إضافات et un pronom suffixe (leçon 4)." },
          { words: [
            { w: "وَ", type: "particule", role: "حرف عطف" },
            { w: "هُوَ", type: "pronom", role: "ضمير منفصل (« il ») · مبتدأ" },
            { w: "نَبِيٌّ", type: "nom", role: "خبر · رَفْع · نكرة (ـٌ)" },
            { w: "كَرِيمٌ", type: "nom", role: "نعت — adjectif · رَفْع · نكرة" },
            { w: "مِنْ", type: "particule", role: "حرف جر" },
            { w: "أُولِي", type: "nom", role: "مجرور · مضاف" },
            { w: "العَزْمِ", type: "nom", role: "مضاف إليه · جرّ · معرفة" },
          ], takeaway: "نَبِيٌّ كَرِيمٌ : nom indéfini + son نعت, accordés (leçon 4)." },
        ],
      },
    ],
  },

  {
    id: "yusuf",
    n: 2,
    title: "يُوسُف عَلَيْهِ السَّلَام",
    titleFr: "Le prophète Yūsuf (Joseph)",
    subtitle: "Du rêve d'enfance jusqu'aux retrouvailles — أَحْسَنُ القَصَص",
    cards: [
      {
        ar: ["رَأى يُوسُفُ فِي المَنامِ أَحَدَ عَشَرَ كَوْكَبًا وَالشَّمْسَ وَالقَمَرَ.", "كانُوا يَسْجُدُونَ لَهُ."],
        fr: ["Yūsuf vit en songe onze étoiles, le soleil et la lune.", "Ils se prosternaient devant lui."],
        refs: ["12:4"],
        an: [
          { words: [
            { w: "رَأى", type: "verbe", role: "فعل (« vit »)" },
            { w: "يُوسُفُ", type: "nom", role: "فاعل · رَفْع (diptote, sans tanwin)" },
            { w: "فِي", type: "particule", role: "حرف جر" },
            { w: "المَنامِ", type: "nom", role: "مجرور · معرفة (« le songe »)" },
            { w: "أَحَدَ عَشَرَ", type: "nom", role: "مفعول به · نَصْب (« onze »)" },
            { w: "كَوْكَبًا", type: "nom", role: "تمييز · نَصْب · نكرة (ـً)" },
            { w: "وَالشَّمْسَ", type: "nom", role: "و + مفعول به · نَصْب · معرفة" },
            { w: "وَالقَمَرَ", type: "nom", role: "و + مفعول به · نَصْب · معرفة" },
          ], takeaway: "فعل + فاعل + مفعول به ; le sujet يُوسُفُ est au cas رفع (leçons 1 & 3)." },
          { words: [
            { w: "كانُوا", type: "verbe", role: "كان + و (« ils étaient »)" },
            { w: "يَسْجُدُونَ", type: "verbe", role: "فعل مضارع (« se prosternent »)" },
            { w: "لَـ", type: "particule", role: "حرف جر" },
            { w: "ـهُ", type: "pronom", role: "« lui » · مجرور" },
          ], takeaway: "Après لـ, le pronom suffixe est au cas جرّ (leçon 3)." },
        ],
      },
      {
        ar: ["حَذَّرَهُ أَبُوهُ يَعْقُوبُ أَنْ يُخْبِرَ إِخْوَتَهُ.", "لِأَنَّ الشَّيْطانَ عَدُوٌّ مُبِينٌ لِلْإِنْسانِ."],
        fr: ["Son père Yaʿqūb l'avertit de ne pas en informer ses frères.", "Car le diable est un ennemi déclaré pour l'homme."],
        refs: ["12:5"],
        an: [
          { words: [
            { w: "حَذَّرَ", type: "verbe", role: "فعل (« avertit »)" },
            { w: "ـهُ", type: "pronom", role: "مفعول به (« le »)" },
            { w: "أَبُو", type: "nom", role: "فاعل · رَفْع · مضاف" },
            { w: "ـهُ", type: "pronom", role: "« son » · مضاف إليه" },
            { w: "يَعْقُوبُ", type: "nom", role: "بدل — apposition (nom propre)" },
            { w: "أَنْ", type: "particule", role: "حرف مصدري" },
            { w: "يُخْبِرَ", type: "verbe", role: "فعل (« informer »)" },
            { w: "إِخْوَةَ", type: "nom", role: "مفعول به · نَصْب · مضاف" },
            { w: "ـهُ", type: "pronom", role: "« ses » · مضاف إليه" },
          ], takeaway: "أَبُوهُ et إِخْوَتَهُ : deux إضافات avec pronom suffixe (leçons 2 & 4)." },
          { words: [
            { w: "لِأَنَّ", type: "particule", role: "حرف تعليل (« car »)" },
            { w: "الشَّيْطانَ", type: "nom", role: "اسم أنّ · نَصْب · معرفة" },
            { w: "عَدُوٌّ", type: "nom", role: "خبر أنّ · رَفْع · نكرة (ـٌ)" },
            { w: "مُبِينٌ", type: "nom", role: "نعت — adjectif · رَفْع · نكرة" },
            { w: "لِلْإِنْسانِ", type: "nom", role: "لـ + الإنسان · مجرور · معرفة" },
          ], takeaway: "Après لِأَنَّ, le nom الشَّيْطانَ passe au cas نصب (اسم أنّ) — leçon 3." },
        ],
      },
      {
        ar: ["حَسَدَ الإِخْوَةُ يُوسُفَ لِمَحَبَّةِ أَبِيهِمْ لَهُ.", "اتَّفَقُوا عَلى أَنْ يُلْقُوهُ فِي البِئْرِ."],
        fr: ["Les frères jalousèrent Yūsuf à cause de l'amour de leur père pour lui.", "Ils se mirent d'accord pour le jeter dans le puits."],
        refs: ["12:15"],
        an: [
          { words: [
            { w: "حَسَدَ", type: "verbe", role: "فعل (« jalousèrent »)" },
            { w: "الإِخْوَةُ", type: "nom", role: "فاعل · رَفْع · معرفة" },
            { w: "يُوسُفَ", type: "nom", role: "مفعول به · نَصْب (diptote)" },
            { w: "لِـ", type: "particule", role: "حرف جر (« à cause de »)" },
            { w: "مَحَبَّةِ", type: "nom", role: "مجرور · مضاف" },
            { w: "أَبِي", type: "nom", role: "مضاف إليه · مضاف" },
            { w: "ـهِمْ", type: "pronom", role: "« leur » · مضاف إليه" },
            { w: "لَـ", type: "particule", role: "حرف جر" },
            { w: "ـهُ", type: "pronom", role: "« lui »" },
          ], takeaway: "Chaîne d'إضافة : مَحَبَّةِ أَبِيهِمْ — « l'amour de leur père » (leçon 2)." },
          { words: [
            { w: "اتَّفَقُوا", type: "verbe", role: "فعل + و (« se mirent d'accord »)" },
            { w: "عَلى", type: "particule", role: "حرف جر" },
            { w: "أَنْ", type: "particule", role: "حرف مصدري" },
            { w: "يُلْقُو", type: "verbe", role: "فعل (« jeter »)" },
            { w: "ـهُ", type: "pronom", role: "مفعول به (« le »)" },
            { w: "فِي", type: "particule", role: "حرف جر" },
            { w: "البِئْرِ", type: "nom", role: "مجرور · معرفة (« le puits »)" },
          ], takeaway: "Deux حروف جرّ (على, في) : les noms qui suivent sont au cas جرّ (leçon 3)." },
        ],
      },
      {
        ar: ["ذَبَحُوا شاةً وَلَطَّخُوا قَمِيصَ يُوسُفَ بِدَمِها.", "رَجَعُوا إِلى أَبِيهِمْ يَبْكُونَ وَقالُوا: أَكَلَهُ الذِّئْبُ."],
        fr: ["Ils égorgèrent une brebis et tachèrent la tunique de Yūsuf de son sang.", "Ils revinrent vers leur père en pleurant, disant : le loup l'a mangé."],
        refs: ["12:18"],
        an: [
          { words: [
            { w: "ذَبَحُوا", type: "verbe", role: "فعل + و (« égorgèrent »)" },
            { w: "شاةً", type: "nom", role: "مفعول به · نَصْب · نكرة (ـً)" },
            { w: "وَلَطَّخُوا", type: "verbe", role: "و + verbe (« tachèrent »)" },
            { w: "قَمِيصَ", type: "nom", role: "مفعول به · مضاف" },
            { w: "يُوسُفَ", type: "nom", role: "مضاف إليه (diptote)" },
            { w: "بِـ", type: "particule", role: "حرف جر" },
            { w: "دَمِ", type: "nom", role: "مجرور · مضاف" },
            { w: "ـها", type: "pronom", role: "« sa » · مضاف إليه" },
          ], takeaway: "قَمِيصَ يُوسُفَ et دَمِها : deux إضافات (leçon 2)." },
          { words: [
            { w: "رَجَعُوا", type: "verbe", role: "فعل + و (« revinrent »)" },
            { w: "إِلى", type: "particule", role: "حرف جر" },
            { w: "أَبِي", type: "nom", role: "مجرور · مضاف" },
            { w: "ـهِمْ", type: "pronom", role: "« leur » · مضاف إليه" },
            { w: "يَبْكُونَ", type: "verbe", role: "فعل حال (« en pleurant »)" },
            { w: "وَقالُوا", type: "verbe", role: "و + قال + و (« et dirent »)" },
            { w: "أَكَلَ", type: "verbe", role: "فعل (« a mangé »)" },
            { w: "ـهُ", type: "pronom", role: "مفعول به (« le »)" },
            { w: "الذِّئْبُ", type: "nom", role: "فاعل · رَفْع · معرفة (« le loup »)" },
          ], takeaway: "Ordre inversé (verbe + objet + sujet) ; الذِّئْبُ reste فاعل au cas رفع (leçon 3)." },
        ],
      },
      {
        ar: ["جاءَتْ قافِلَةٌ وَأَرْسَلَتْ رَجُلًا لِيَأْتِيَ بِالماءِ.", "أَدْلى دَلْوَهُ فِي البِئْرِ فَخَرَجَ يُوسُفُ."],
        fr: ["Une caravane arriva et envoya un homme chercher de l'eau.", "Il descendit son seau dans le puits, et Yūsuf en sortit."],
        refs: ["12:19"],
        an: [
          { words: [
            { w: "جاءَتْ", type: "verbe", role: "فعل (« arriva »)" },
            { w: "قافِلَةٌ", type: "nom", role: "فاعل · رَفْع · نكرة (ـٌ)" },
            { w: "وَأَرْسَلَتْ", type: "verbe", role: "و + verbe (« envoya »)" },
            { w: "رَجُلًا", type: "nom", role: "مفعول به · نَصْب · نكرة (ـً)" },
            { w: "لِـ", type: "particule", role: "حرف تعليل (« pour »)" },
            { w: "يَأْتِيَ", type: "verbe", role: "فعل (« venir »)" },
            { w: "بِالماءِ", type: "nom", role: "بـ + الماء · مجرور · معرفة" },
          ], takeaway: "قافِلَةٌ (indéfinie, tanwin) et رَجُلًا (indéfini) — leçon 1." },
          { words: [
            { w: "أَدْلى", type: "verbe", role: "فعل (« fit descendre »)" },
            { w: "دَلْوَ", type: "nom", role: "مفعول به · مضاف" },
            { w: "ـهُ", type: "pronom", role: "« son » · مضاف إليه" },
            { w: "فِي", type: "particule", role: "حرف جر" },
            { w: "البِئْرِ", type: "nom", role: "مجرور · معرفة" },
            { w: "فَـ", type: "particule", role: "حرف عطف (« alors »)" },
            { w: "خَرَجَ", type: "verbe", role: "فعل (« sortit »)" },
            { w: "يُوسُفُ", type: "nom", role: "فاعل · رَفْع" },
          ], takeaway: "دَلْوَهُ : nom + suffixe ـه = إضافة, cas نصب (leçons 2 & 4)." },
        ],
      },
      {
        ar: ["باعُوا يُوسُفَ بِثَمَنٍ قَلِيلٍ فِي مِصْرَ.", "اِشْتَراهُ العَزِيزُ وَقالَ لِزَوْجَتِهِ: أَكْرِمِي مَقامَهُ."],
        fr: ["Ils vendirent Yūsuf pour un prix dérisoire en Égypte.", "Al-ʿAzīz l'acheta et dit à son épouse : accueille-le avec honneur."],
        refs: ["12:21"],
        an: [
          { words: [
            { w: "باعُوا", type: "verbe", role: "فعل + و (« vendirent »)" },
            { w: "يُوسُفَ", type: "nom", role: "مفعول به · نَصْب (diptote)" },
            { w: "بِـ", type: "particule", role: "حرف جر (« pour »)" },
            { w: "ثَمَنٍ", type: "nom", role: "مجرور · نكرة (ـٍ)" },
            { w: "قَلِيلٍ", type: "nom", role: "نعت — adjectif · جرّ · نكرة" },
            { w: "فِي", type: "particule", role: "حرف جر" },
            { w: "مِصْرَ", type: "nom", role: "مجرور (diptote, sans tanwin)" },
          ], takeaway: "ثَمَنٍ قَلِيلٍ : nom + adjectif accordés (indéfini, جرّ) — leçon 4." },
          { words: [
            { w: "اِشْتَرا", type: "verbe", role: "فعل (« acheta »)" },
            { w: "ـهُ", type: "pronom", role: "مفعول به (« le »)" },
            { w: "العَزِيزُ", type: "nom", role: "فاعل · رَفْع · معرفة" },
            { w: "وَقالَ", type: "verbe", role: "و + verbe" },
            { w: "لِـ", type: "particule", role: "حرف جر" },
            { w: "زَوْجَةِ", type: "nom", role: "مجرور · مضاف" },
            { w: "ـهِ", type: "pronom", role: "« son » · مضاف إليه" },
          ], takeaway: "زَوْجَتِهِ : nom + pronom suffixe (إضافة au cas جرّ) — leçons 2 & 4." },
        ],
      },
      {
        ar: ["راوَدَتْ زَوْجَةُ العَزِيزِ يُوسُفَ عَنْ نَفْسِهِ.", "قالَ يُوسُفُ: مَعاذَ اللَّهِ."],
        fr: ["L'épouse d'al-ʿAzīz tenta de séduire Yūsuf.", "Yūsuf dit : qu'Allah m'en préserve."],
        refs: ["12:23"],
        an: [
          { words: [
            { w: "راوَدَتْ", type: "verbe", role: "فعل (« tenta de séduire »)" },
            { w: "زَوْجَةُ", type: "nom", role: "فاعل · رَفْع · مضاف" },
            { w: "العَزِيزِ", type: "nom", role: "مضاف إليه · جرّ · معرفة" },
            { w: "يُوسُفَ", type: "nom", role: "مفعول به · نَصْب" },
            { w: "عَنْ", type: "particule", role: "حرف جر" },
            { w: "نَفْسِ", type: "nom", role: "مجرور · مضاف" },
            { w: "ـهِ", type: "pronom", role: "« sa » · مضاف إليه" },
          ], takeaway: "زَوْجَةُ العَزِيزِ : une إضافة définie ; le مُضَاف reste sans الـ (leçon 2)." },
          { words: [
            { w: "قالَ", type: "verbe", role: "فعل (« dit »)" },
            { w: "يُوسُفُ", type: "nom", role: "فاعل · رَفْع" },
            { w: "مَعاذَ", type: "nom", role: "مفعول مطلق · نَصْب · مضاف" },
            { w: "اللَّهِ", type: "nom", role: "مضاف إليه · جرّ" },
          ], takeaway: "مَعاذَ اللَّهِ : formule fixe, une إضافة au cas نصب/جرّ (leçon 2)." },
        ],
      },
      {
        ar: ["هَرَبَ يُوسُفُ نَحْوَ البابِ فَقَدَّتْ قَمِيصَهُ مِنَ الخَلْفِ.", "وَجَدا زَوْجَها عِنْدَ البابِ."],
        fr: ["Yūsuf s'enfuit vers la porte, et elle déchira sa tunique par-derrière.", "Ils trouvèrent son mari près de la porte."],
        refs: ["12:25"],
        an: [
          { words: [
            { w: "هَرَبَ", type: "verbe", role: "فعل (« s'enfuit »)" },
            { w: "يُوسُفُ", type: "nom", role: "فاعل · رَفْع" },
            { w: "نَحْوَ", type: "nom", role: "ظرف مكان · نَصْب" },
            { w: "البابِ", type: "nom", role: "مجرور · معرفة (« la porte »)" },
            { w: "فَـ", type: "particule", role: "حرف عطف" },
            { w: "قَدَّتْ", type: "verbe", role: "فعل (« déchira »)" },
            { w: "قَمِيصَ", type: "nom", role: "مفعول به · مضاف" },
            { w: "ـهُ", type: "pronom", role: "« sa » · مضاف إليه" },
            { w: "مِنَ", type: "particule", role: "حرف جر" },
            { w: "الخَلْفِ", type: "nom", role: "مجرور · معرفة (« l'arrière »)" },
          ], takeaway: "قَمِيصَهُ : nom + suffixe ـه — une إضافة (leçons 2 & 4)." },
          { words: [
            { w: "وَجَدا", type: "verbe", role: "فعل + ا (duel, « ils deux trouvèrent »)" },
            { w: "زَوْجَ", type: "nom", role: "مفعول به · مضاف" },
            { w: "ـها", type: "pronom", role: "« son » · مضاف إليه" },
            { w: "عِنْدَ", type: "nom", role: "ظرف مكان · نَصْب (« près de »)" },
            { w: "البابِ", type: "nom", role: "مجرور · معرفة" },
          ], takeaway: "وَجَدا : verbe au duel (leçon 3) ; زَوْجَها : إضافة." },
        ],
      },
      {
        ar: ["دَعَتْ زَوْجَةُ العَزِيزِ نِساءَ المَدينَةِ إِلى وَلِيمَةٍ.", "لَمّا رَأَيْنَ يُوسُفَ قَطَّعْنَ أَيْدِيَهُنَّ مِنْ جَمالِهِ."],
        fr: ["L'épouse d'al-ʿAzīz invita les femmes de la ville à un banquet.", "Lorsqu'elles virent Yūsuf, elles se coupèrent les mains tant sa beauté était grande."],
        refs: ["12:31"],
        an: [
          { words: [
            { w: "دَعَتْ", type: "verbe", role: "فعل (« invita »)" },
            { w: "زَوْجَةُ", type: "nom", role: "فاعل · رَفْع · مضاف" },
            { w: "العَزِيزِ", type: "nom", role: "مضاف إليه · جرّ" },
            { w: "نِساءَ", type: "nom", role: "مفعول به · نَصْب · مضاف" },
            { w: "المَدينَةِ", type: "nom", role: "مضاف إليه · جرّ · معرفة" },
            { w: "إِلى", type: "particule", role: "حرف جر" },
            { w: "وَلِيمَةٍ", type: "nom", role: "مجرور · نكرة (ـٍ)" },
          ], takeaway: "Deux إضافات successives : زَوْجَةُ العَزِيزِ, نِساءَ المَدينَةِ (leçon 2)." },
          { words: [
            { w: "لَمّا", type: "particule", role: "حرف (« lorsque »)" },
            { w: "رَأَيْنَ", type: "verbe", role: "فعل + ن (féminin pluriel)" },
            { w: "يُوسُفَ", type: "nom", role: "مفعول به · نَصْب" },
            { w: "قَطَّعْنَ", type: "verbe", role: "فعل + ن (« coupèrent »)" },
            { w: "أَيْدِيَ", type: "nom", role: "مفعول به · مضاف" },
            { w: "ـهُنَّ", type: "pronom", role: "« leurs » (féminin pluriel) · مضاف إليه" },
            { w: "مِنْ", type: "particule", role: "حرف جر" },
            { w: "جَمالِ", type: "nom", role: "مجرور · مضاف" },
            { w: "ـهِ", type: "pronom", role: "« sa » · مضاف إليه" },
          ], takeaway: "ـهُنَّ = suffixe féminin pluriel (« leurs ») — leçon 4." },
        ],
      },
      {
        ar: ["فَضَّلَ يُوسُفُ السِّجْنَ عَلى مَعْصِيَةِ اللَّهِ.", "دَعا رَبَّهُ أَنْ يَصْرِفَ عَنْهُ كَيْدَهُنَّ."],
        fr: ["Yūsuf préféra la prison à la désobéissance envers Allah.", "Il invoqua son Seigneur pour qu'Il détourne de lui leur ruse."],
        refs: ["12:33"],
        an: [
          { words: [
            { w: "فَضَّلَ", type: "verbe", role: "فعل (« préféra »)" },
            { w: "يُوسُفُ", type: "nom", role: "فاعل · رَفْع" },
            { w: "السِّجْنَ", type: "nom", role: "مفعول به · نَصْب · معرفة" },
            { w: "عَلى", type: "particule", role: "حرف جر" },
            { w: "مَعْصِيَةِ", type: "nom", role: "مجرور · مضاف" },
            { w: "اللَّهِ", type: "nom", role: "مضاف إليه · جرّ" },
          ], takeaway: "مَعْصِيَةِ اللَّهِ : une إضافة au cas جرّ après على (leçons 2 & 3)." },
          { words: [
            { w: "دَعا", type: "verbe", role: "فعل (« invoqua »)" },
            { w: "رَبَّ", type: "nom", role: "مفعول به · مضاف" },
            { w: "ـهُ", type: "pronom", role: "« son » · مضاف إليه" },
            { w: "أَنْ", type: "particule", role: "حرف مصدري" },
            { w: "يَصْرِفَ", type: "verbe", role: "فعل (« détourne »)" },
            { w: "عَنْـ", type: "particule", role: "حرف جر" },
            { w: "ـهُ", type: "pronom", role: "« lui » · مجرور" },
            { w: "كَيْدَ", type: "nom", role: "مفعول به · مضاف" },
            { w: "ـهُنَّ", type: "pronom", role: "« leur » (fém. pl.) · مضاف إليه" },
          ], takeaway: "رَبَّهُ et كَيْدَهُنَّ : deux إضافات avec pronoms suffixes (leçons 2 & 4)." },
        ],
      },
      {
        ar: ["دَخَلَ السِّجْنَ مَعَ يُوسُفَ فَتَيانِ.", "قالا: رَأَيْنا فِي المَنامِ رُؤْيَتَيْنِ، فَأَخْبِرْنا بِتَأْوِيلِهِما."],
        fr: ["Deux jeunes hommes entrèrent en prison avec Yūsuf.", "Ils dirent : nous avons vu deux songes, alors interprète-nous-les."],
        refs: ["12:36"],
        an: [
          { words: [
            { w: "دَخَلَ", type: "verbe", role: "فعل (« entrèrent »)" },
            { w: "السِّجْنَ", type: "nom", role: "مفعول به · نَصْب · معرفة" },
            { w: "مَعَ", type: "nom", role: "ظرف (« avec ») · نَصْب" },
            { w: "يُوسُفَ", type: "nom", role: "مضاف إليه (diptote)" },
            { w: "فَتَيانِ", type: "nom", role: "فاعل · duel · رَفْع (ـانِ)" },
          ], takeaway: "فَتَيانِ : le duel au cas رفع, terminaison ـانِ (leçon 3)." },
          { words: [
            { w: "قالا", type: "verbe", role: "فعل duel (« ils deux dirent »)" },
            { w: "رَأَيْنا", type: "verbe", role: "فعل + نا (« nous vîmes »)" },
            { w: "فِي", type: "particule", role: "حرف جر" },
            { w: "المَنامِ", type: "nom", role: "مجرور · معرفة" },
            { w: "رُؤْيَتَيْنِ", type: "nom", role: "مفعول به · duel · نَصْب (ـَيْنِ)" },
            { w: "فَـ", type: "particule", role: "حرف" },
            { w: "أَخْبِرْ", type: "verbe", role: "فعل أمر (« informe »)" },
            { w: "ـنا", type: "pronom", role: "« nous »" },
            { w: "بِـ", type: "particule", role: "حرف جر" },
            { w: "تَأْوِيلِ", type: "nom", role: "مجرور · مضاف" },
            { w: "ـهِما", type: "pronom", role: "« leurs deux » (duel) · مضاف إليه" },
          ], takeaway: "قالا, رُؤْيَتَيْنِ, ـهِما : trois formes du duel (leçon 3)." },
        ],
      },
      {
        ar: ["أَخْبَرَهُما يُوسُفُ بِتَأْوِيلِ الرُّؤْيا.", "قالَ: أَحَدُكُما يَسْقِي رَبَّهُ خَمْرًا، وَالآخَرُ يُصْلَبُ."],
        fr: ["Yūsuf leur donna l'interprétation de leur rêve.", "Il dit : l'un de vous deux servira du vin à son maître, et l'autre sera crucifié."],
        refs: ["12:41"],
        an: [
          { words: [
            { w: "أَخْبَرَ", type: "verbe", role: "فعل (« informa »)" },
            { w: "ـهُما", type: "pronom", role: "مفعول به duel (« eux deux »)" },
            { w: "يُوسُفُ", type: "nom", role: "فاعل · رَفْع" },
            { w: "بِـ", type: "particule", role: "حرف جر" },
            { w: "تَأْوِيلِ", type: "nom", role: "مجرور · مضاف" },
            { w: "الرُّؤْيا", type: "nom", role: "مضاف إليه · معرفة" },
          ], takeaway: "تَأْوِيلِ الرُّؤْيا : une إضافة définie ; le مُضَاف reste sans الـ (leçon 2)." },
          { words: [
            { w: "قالَ", type: "verbe", role: "فعل" },
            { w: "أَحَدُ", type: "nom", role: "مبتدأ · رَفْع · مضاف" },
            { w: "ـكُما", type: "pronom", role: "« vous deux » · مضاف إليه" },
            { w: "يَسْقِي", type: "verbe", role: "فعل — خبر (« sert »)" },
            { w: "رَبَّ", type: "nom", role: "مفعول به · مضاف" },
            { w: "ـهُ", type: "pronom", role: "« son » · مضاف إليه" },
            { w: "خَمْرًا", type: "nom", role: "مفعول به ثانٍ · نَصْب · نكرة" },
            { w: "وَالآخَرُ", type: "nom", role: "و + مبتدأ · رَفْع · معرفة" },
            { w: "يُصْلَبُ", type: "verbe", role: "فعل مبني للمجهول — خبر (« sera crucifié »)" },
          ], takeaway: "Deux phrases nominales : مبتدأ (nom) + خبر (verbe) — leçon 2." },
        ],
      },
      {
        ar: ["رَأى المَلِكُ فِي المَنامِ سَبْعَ بَقَراتٍ سِمانٍ يَأْكُلُهُنَّ سَبْعٌ عِجافٌ.", "وَسَبْعَ سُنْبُلاتٍ خُضْرٍ وَأُخَرَ يابِساتٍ."],
        fr: ["Le roi vit en songe sept vaches grasses dévorées par sept maigres.", "Et sept épis verts, et d'autres desséchés."],
        refs: ["12:43"],
        an: [
          { words: [
            { w: "رَأى", type: "verbe", role: "فعل (« vit »)" },
            { w: "المَلِكُ", type: "nom", role: "فاعل · رَفْع · معرفة" },
            { w: "فِي", type: "particule", role: "حرف جر" },
            { w: "المَنامِ", type: "nom", role: "مجرور · معرفة" },
            { w: "سَبْعَ", type: "nom", role: "مفعول به · نَصْب · مضاف" },
            { w: "بَقَراتٍ", type: "nom", role: "مضاف إليه · جرّ · جمع مؤنث (ـاتٍ)" },
            { w: "سِمانٍ", type: "nom", role: "نعت · جرّ (« grasses »)" },
            { w: "يَأْكُلُ", type: "verbe", role: "فعل" },
            { w: "ـهُنَّ", type: "pronom", role: "مفعول به (fém. pl.)" },
            { w: "سَبْعٌ", type: "nom", role: "فاعل · رَفْع · نكرة (ـٌ)" },
            { w: "عِجافٌ", type: "nom", role: "نعت · رَفْع (« maigres »)" },
          ], takeaway: "سَبْعَ بَقَراتٍ : une إضافة (« sept vaches ») — leçon 2." },
          { words: [
            { w: "وَسَبْعَ", type: "nom", role: "و + مفعول به · مضاف" },
            { w: "سُنْبُلاتٍ", type: "nom", role: "مضاف إليه · جمع مؤنث" },
            { w: "خُضْرٍ", type: "nom", role: "نعت (« verts »)" },
            { w: "وَأُخَرَ", type: "nom", role: "و + معطوف · نَصْب (diptote)" },
            { w: "يابِساتٍ", type: "nom", role: "نعت · جمع مؤنث (« desséchés »)" },
          ], takeaway: "سُنْبُلاتٍ, يابِساتٍ : pluriels féminins sains (ـات) — leçon 3." },
        ],
      },
      {
        ar: ["فَسَّرَ يُوسُفُ الرُّؤْيا: سَبْعُ سِنِينَ خِصْبٍ ثُمَّ سَبْعُ سِنِينَ جَدْبٍ.", "طَلَبَ مِنَ المَلِكِ أَنْ يَجْعَلَهُ عَلى خَزائِنِ الأَرْضِ."],
        fr: ["Yūsuf interpréta le rêve : sept années d'abondance puis sept années de disette.", "Il demanda au roi de l'établir sur les greniers du pays."],
        refs: ["12:47", "12:55"],
        an: [
          { words: [
            { w: "فَسَّرَ", type: "verbe", role: "فعل (« interpréta »)" },
            { w: "يُوسُفُ", type: "nom", role: "فاعل · رَفْع" },
            { w: "الرُّؤْيا", type: "nom", role: "مفعول به · معرفة" },
            { w: "سَبْعُ", type: "nom", role: "خبر (« sept ») · رَفْع · مضاف" },
            { w: "سِنِينَ", type: "nom", role: "مضاف إليه · جرّ · جمع" },
            { w: "خِصْبٍ", type: "nom", role: "مضاف إليه (chaîne) · جرّ · نكرة" },
            { w: "ثُمَّ", type: "particule", role: "حرف عطف (« puis »)" },
            { w: "سَبْعُ سِنِينَ جَدْبٍ", type: "nom", role: "معطوف : même construction (« disette »)" },
          ], takeaway: "Chaîne d'إضافة : سَبْعُ سِنِينَ خِصْبٍ (leçon 2)." },
          { words: [
            { w: "طَلَبَ", type: "verbe", role: "فعل (« demanda »)" },
            { w: "مِنَ", type: "particule", role: "حرف جر" },
            { w: "المَلِكِ", type: "nom", role: "مجرور · معرفة" },
            { w: "أَنْ", type: "particule", role: "حرف مصدري" },
            { w: "يَجْعَلَ", type: "verbe", role: "فعل (« établir »)" },
            { w: "ـهُ", type: "pronom", role: "مفعول به (« le »)" },
            { w: "عَلى", type: "particule", role: "حرف جر" },
            { w: "خَزائِنِ", type: "nom", role: "مجرور · مضاف" },
            { w: "الأَرْضِ", type: "nom", role: "مضاف إليه · معرفة" },
          ], takeaway: "خَزائِنِ الأَرْضِ : إضافة définie ; le مُضَاف garde sa forme (leçon 2)." },
        ],
      },
      {
        ar: ["جاءَ إِخْوَةُ يُوسُفَ إِلى مِصْرَ يَطْلُبُونَ الطَّعامَ.", "عَرَفَهُمْ يُوسُفُ وَهُمْ لا يَعْرِفُونَهُ."],
        fr: ["Les frères de Yūsuf vinrent en Égypte pour demander de la nourriture.", "Yūsuf les reconnut, mais eux ne le reconnurent pas."],
        refs: ["12:58"],
        an: [
          { words: [
            { w: "جاءَ", type: "verbe", role: "فعل (« vinrent »)" },
            { w: "إِخْوَةُ", type: "nom", role: "فاعل · رَفْع · مضاف" },
            { w: "يُوسُفَ", type: "nom", role: "مضاف إليه (diptote)" },
            { w: "إِلى", type: "particule", role: "حرف جر" },
            { w: "مِصْرَ", type: "nom", role: "مجرور (diptote)" },
            { w: "يَطْلُبُونَ", type: "verbe", role: "فعل حال + و (« demandant »)" },
            { w: "الطَّعامَ", type: "nom", role: "مفعول به · نَصْب · معرفة" },
          ], takeaway: "إِخْوَةُ يُوسُفَ : une إضافة (« les frères de Yūsuf ») — leçon 2." },
          { words: [
            { w: "عَرَفَ", type: "verbe", role: "فعل (« reconnut »)" },
            { w: "ـهُمْ", type: "pronom", role: "مفعول به (« les »)" },
            { w: "يُوسُفُ", type: "nom", role: "فاعل · رَفْع" },
            { w: "وَهُمْ", type: "pronom", role: "و الحال + « ils »" },
            { w: "لا", type: "particule", role: "حرف نفي" },
            { w: "يَعْرِفُونَ", type: "verbe", role: "فعل + و" },
            { w: "ـهُ", type: "pronom", role: "مفعول به (« le »)" },
          ], takeaway: "هُمْ = pronom isolé, sujet d'une phrase d'état (حال) — leçon 4." },
        ],
      },
      {
        ar: ["وَضَعَ يُوسُفُ الصُّواعَ فِي مَتاعِ أَخِيهِ.", "أَمَرَ الحُرّاسَ أَنْ يُوقِفُوا القافِلَةَ."],
        fr: ["Yūsuf plaça la coupe dans les affaires de son frère.", "Il ordonna aux gardes d'arrêter la caravane."],
        refs: ["12:70"],
        an: [
          { words: [
            { w: "وَضَعَ", type: "verbe", role: "فعل (« plaça »)" },
            { w: "يُوسُفُ", type: "nom", role: "فاعل · رَفْع" },
            { w: "الصُّواعَ", type: "nom", role: "مفعول به · نَصْب · معرفة" },
            { w: "فِي", type: "particule", role: "حرف جر" },
            { w: "مَتاعِ", type: "nom", role: "مجرور · مضاف" },
            { w: "أَخِي", type: "nom", role: "مضاف إليه · مضاف" },
            { w: "ـهِ", type: "pronom", role: "« son » · مضاف إليه" },
          ], takeaway: "مَتاعِ أَخِيهِ : chaîne d'إضافة (« les affaires de son frère ») — leçon 2." },
          { words: [
            { w: "أَمَرَ", type: "verbe", role: "فعل (« ordonna »)" },
            { w: "الحُرّاسَ", type: "nom", role: "مفعول به · نَصْب · معرفة" },
            { w: "أَنْ", type: "particule", role: "حرف مصدري" },
            { w: "يُوقِفُوا", type: "verbe", role: "فعل + و (« arrêter »)" },
            { w: "القافِلَةَ", type: "nom", role: "مفعول به · نَصْب · معرفة" },
          ], takeaway: "الحُرّاسَ et القافِلَةَ : deux objets définis au cas نصب (leçons 1 & 3)." },
        ],
      },
      {
        ar: ["حَزِنَ يَعْقُوبُ حُزْنًا شَديدًا عَلى فِراقِ ابْنَيْهِ.", "قالَ: لا تَيْأَسُوا مِنْ رَحْمَةِ اللَّهِ."],
        fr: ["Yaʿqūb éprouva une immense tristesse pour la séparation de ses deux fils.", "Il dit : ne désespérez pas de la miséricorde d'Allah."],
        refs: ["12:83", "12:87"],
        an: [
          { words: [
            { w: "حَزِنَ", type: "verbe", role: "فعل (« s'attrista »)" },
            { w: "يَعْقُوبُ", type: "nom", role: "فاعل · رَفْع (diptote)" },
            { w: "حُزْنًا", type: "nom", role: "مفعول مطلق · نَصْب · نكرة" },
            { w: "شَديدًا", type: "nom", role: "نعت · نَصْب · نكرة" },
            { w: "عَلى", type: "particule", role: "حرف جر" },
            { w: "فِراقِ", type: "nom", role: "مجرور · مضاف" },
            { w: "ابْنَيْ", type: "nom", role: "duel · مضاف" },
            { w: "ـهِ", type: "pronom", role: "« ses » · مضاف إليه" },
          ], takeaway: "ابْنَيْهِ : duel au cas جرّ (ـَيْ) + suffixe — leçons 3 & 4." },
          { words: [
            { w: "قالَ", type: "verbe", role: "فعل" },
            { w: "لا", type: "particule", role: "حرف نهي" },
            { w: "تَيْأَسُوا", type: "verbe", role: "فعل + و (« ne désespérez pas »)" },
            { w: "مِنْ", type: "particule", role: "حرف جر" },
            { w: "رَحْمَةِ", type: "nom", role: "مجرور · مضاف" },
            { w: "اللَّهِ", type: "nom", role: "مضاف إليه · جرّ" },
          ], takeaway: "رَحْمَةِ اللَّهِ : une إضافة au cas جرّ (leçons 2 & 3)." },
        ],
      },
      {
        ar: ["كَشَفَ يُوسُفُ نَفْسَهُ لِإِخْوَتِهِ وَعَفا عَنْهُمْ.", "أَرْسَلَ قَمِيصَهُ إِلى أَبيهِ فَرَجَعَ إِلَيْهِ بَصَرُهُ."],
        fr: ["Yūsuf se dévoila à ses frères et leur pardonna.", "Il envoya sa tunique à son père, et la vue lui revint."],
        refs: ["12:93"],
        an: [
          { words: [
            { w: "كَشَفَ", type: "verbe", role: "فعل (« dévoila »)" },
            { w: "يُوسُفُ", type: "nom", role: "فاعل · رَفْع" },
            { w: "نَفْسَ", type: "nom", role: "مفعول به · مضاف" },
            { w: "ـهُ", type: "pronom", role: "« sa » · مضاف إليه" },
            { w: "لِـ", type: "particule", role: "حرف جر" },
            { w: "إِخْوَةِ", type: "nom", role: "مجرور · مضاف" },
            { w: "ـهِ", type: "pronom", role: "« ses » · مضاف إليه" },
            { w: "وَعَفا", type: "verbe", role: "و + verbe (« pardonna »)" },
            { w: "عَنْـ", type: "particule", role: "حرف جر" },
            { w: "ـهُمْ", type: "pronom", role: "« eux » · مجرور" },
          ], takeaway: "نَفْسَهُ, إِخْوَتِهِ : deux إضافات avec pronoms suffixes (leçons 2 & 4)." },
          { words: [
            { w: "أَرْسَلَ", type: "verbe", role: "فعل (« envoya »)" },
            { w: "قَمِيصَ", type: "nom", role: "مفعول به · مضاف" },
            { w: "ـهُ", type: "pronom", role: "« sa » · مضاف إليه" },
            { w: "إِلى", type: "particule", role: "حرف جر" },
            { w: "أَبِي", type: "nom", role: "مجرور · مضاف" },
            { w: "ـهِ", type: "pronom", role: "« son » · مضاف إليه" },
            { w: "فَـ", type: "particule", role: "حرف عطف" },
            { w: "رَجَعَ", type: "verbe", role: "فعل (« revint »)" },
            { w: "إِلَيْـ", type: "particule", role: "إلى + ـه" },
            { w: "ـهِ", type: "pronom", role: "« lui »" },
            { w: "بَصَرُ", type: "nom", role: "فاعل · رَفْع · مضاف" },
            { w: "ـهُ", type: "pronom", role: "« sa » · مضاف إليه" },
          ], takeaway: "بَصَرُهُ : le sujet, une إضافة au cas رفع (leçons 2, 3, 4)." },
        ],
      },
      {
        ar: ["اِجْتَمَعَتِ العائِلَةُ فِي مِصْرَ وَسَجَدَ الإِخْوَةُ لِيُوسُفَ.", "قالَ يُوسُفُ: هٰذا تَأْوِيلُ رُؤْيايَ مِنْ قَبْلُ."],
        fr: ["La famille se réunit en Égypte, et les frères se prosternèrent devant Yūsuf.", "Yūsuf dit : voici l'interprétation de mon rêve d'autrefois."],
        refs: ["12:100"],
        an: [
          { words: [
            { w: "اِجْتَمَعَتِ", type: "verbe", role: "فعل (« se réunit »)" },
            { w: "العائِلَةُ", type: "nom", role: "فاعل · رَفْع · معرفة" },
            { w: "فِي", type: "particule", role: "حرف جر" },
            { w: "مِصْرَ", type: "nom", role: "مجرور (diptote)" },
            { w: "وَسَجَدَ", type: "verbe", role: "و + verbe (« se prosternèrent »)" },
            { w: "الإِخْوَةُ", type: "nom", role: "فاعل · رَفْع · معرفة" },
            { w: "لِـ", type: "particule", role: "حرف جر" },
            { w: "يُوسُفَ", type: "nom", role: "مجرور (diptote, sans tanwin)" },
          ], takeaway: "Deux verbes coordonnés (و) chacun avec son propre فاعل défini (leçon 1)." },
          { words: [
            { w: "قالَ", type: "verbe", role: "فعل" },
            { w: "يُوسُفُ", type: "nom", role: "فاعل · رَفْع" },
            { w: "هٰذا", type: "nom", role: "اسم إشارة · مبتدأ (leçon 2)" },
            { w: "تَأْوِيلُ", type: "nom", role: "خبر · رَفْع · مضاف" },
            { w: "رُؤْيا", type: "nom", role: "مضاف إليه" },
            { w: "ـيَ", type: "pronom", role: "« mon » · مضاف إليه" },
            { w: "مِنْ", type: "particule", role: "حرف جر" },
            { w: "قَبْلُ", type: "nom", role: "ظرف زمان (« autrefois »)" },
          ], takeaway: "هٰذا تَأْوِيلُ رُؤْيايَ : phrase nominale — démonstratif مبتدأ + خبر (إضافة) — leçons 2 & 4." },
        ],
      },
    ],
  },
];

// frName : nom français court ; surah : nom arabe court (pour les puces)
window.VERSES = {
  "3:45": { surah: "آل عمران", frName: "Âl ʿImrān", ayah: 45,
    ar: "إِذْ قَالَتِ الْمَلَائِكَةُ يَا مَرْيَمُ إِنَّ اللَّهَ يُبَشِّرُكِ بِكَلِمَةٍ مِنْهُ اسْمُهُ الْمَسِيحُ عِيسَى ابْنُ مَرْيَمَ وَجِيهًا فِي الدُّنْيَا وَالْآخِرَةِ وَمِنَ الْمُقَرَّبِينَ",
    fr: "(Rappelle-toi) quand les Anges dirent : « O Marie, voilà qu'Allah t'annonce une parole de Sa part : son nom sera « Al-Masîh », « ʿĪsā », fils de Marie, illustre ici-bas comme dans l'au-delà, et l'un des rapprochés d'Allah ».",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/338.mp3" },
  "3:47": { surah: "آل عمران", frName: "Âl ʿImrān", ayah: 47,
    ar: "قَالَتْ رَبِّ أَنَّىٰ يَكُونُ لِي وَلَدٌ وَلَمْ يَمْسَسْنِي بَشَرٌ ۖ قَالَ كَذَٰلِكِ اللَّهُ يَخْلُقُ مَا يَشَاءُ ۚ إِذَا قَضَىٰ أَمْرًا فَإِنَّمَا يَقُولُ لَهُ كُنْ فَيَكُونُ",
    fr: "- Elle dit : « Seigneur ! Comment aurais-je un enfant, alors qu'aucun homme ne m'a touchée ? » - « C'est ainsi ! » dit-Il. Allah crée ce qu'Il veut. Quand Il décide d'une chose, Il lui dit seulement : « Sois » et elle est aussitôt.",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/340.mp3" },
  "19:16": { surah: "مريم", frName: "Maryam", ayah: 16,
    ar: "وَاذْكُرْ فِي الْكِتَابِ مَرْيَمَ إِذِ انْتَبَذَتْ مِنْ أَهْلِهَا مَكَانًا شَرْقِيًّا",
    fr: "Mentionne, dans le Livre (le Coran), Marie, quand elle se retira de sa famille en un lieu vers l'Orient.",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/2266.mp3" },
  "19:19": { surah: "مريم", frName: "Maryam", ayah: 19,
    ar: "قَالَ إِنَّمَا أَنَا رَسُولُ رَبِّكِ لِأَهَبَ لَكِ غُلَامًا زَكِيًّا",
    fr: "Il dit : « Je suis en fait un Messager de ton Seigneur pour te faire don d'un fils pur ».",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/2269.mp3" },
  "19:22": { surah: "مريم", frName: "Maryam", ayah: 22,
    ar: "۞ فَحَمَلَتْهُ فَانْتَبَذَتْ بِهِ مَكَانًا قَصِيًّا",
    fr: "Elle devint donc enceinte [de l'enfant], et elle se retira avec lui en un lieu éloigné.",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/2272.mp3" },
  "19:23": { surah: "مريم", frName: "Maryam", ayah: 23,
    ar: "فَأَجَاءَهَا الْمَخَاضُ إِلَىٰ جِذْعِ النَّخْلَةِ قَالَتْ يَا لَيْتَنِي مِتُّ قَبْلَ هَٰذَا وَكُنْتُ نَسْيًا مَنْسِيًّا",
    fr: "Puis les douleurs de l'enfantement l'amenèrent au tronc du palmier, et elle dit : « Malheur à moi ! Que je fusse morte avant cet instant ! Et que je fusse totalement oubliée ! »",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/2273.mp3" },
  "19:24": { surah: "مريم", frName: "Maryam", ayah: 24,
    ar: "فَنَادَاهَا مِنْ تَحْتِهَا أَلَّا تَحْزَنِي قَدْ جَعَلَ رَبُّكِ تَحْتَكِ سَرِيًّا",
    fr: "Alors, il l'appela d'au-dessous d'elle, [lui disant :] « Ne t'afflige pas. Ton Seigneur a placé à tes pieds une source.",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/2274.mp3" },
  "19:25": { surah: "مريم", frName: "Maryam", ayah: 25,
    ar: "وَهُزِّي إِلَيْكِ بِجِذْعِ النَّخْلَةِ تُسَاقِطْ عَلَيْكِ رُطَبًا جَنِيًّا",
    fr: "Secoue vers toi le tronc du palmier : il fera tomber sur toi des dattes fraîches et mûres.",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/2275.mp3" },
  "19:26": { surah: "مريم", frName: "Maryam", ayah: 26,
    ar: "فَكُلِي وَاشْرَبِي وَقَرِّي عَيْنًا ۖ فَإِمَّا تَرَيِنَّ مِنَ الْبَشَرِ أَحَدًا فَقُولِي إِنِّي نَذَرْتُ لِلرَّحْمَٰنِ صَوْمًا فَلَنْ أُكَلِّمَ الْيَوْمَ إِنْسِيًّا",
    fr: "Mange donc et bois et que ton œil se réjouisse ! Si tu vois quelqu'un d'entre les humains, dis [lui :] « Assurément, j'ai voué un jeûne au Tout Miséricordieux : je ne parlerai donc aujourd'hui à aucun être humain ».",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/2276.mp3" },
  "19:29": { surah: "مريم", frName: "Maryam", ayah: 29,
    ar: "فَأَشَارَتْ إِلَيْهِ ۖ قَالُوا كَيْفَ نُكَلِّمُ مَنْ كَانَ فِي الْمَهْدِ صَبِيًّا",
    fr: "Elle fit alors un signe vers lui [le bébé]. Ils dirent : « Comment parlerions-nous à un bébé au berceau ? »",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/2279.mp3" },
  "19:30": { surah: "مريم", frName: "Maryam", ayah: 30,
    ar: "قَالَ إِنِّي عَبْدُ اللَّهِ آتَانِيَ الْكِتَابَ وَجَعَلَنِي نَبِيًّا",
    fr: "Mais (le bébé) dit : « Je suis vraiment le serviteur d'Allah. Il m'a donné le Livre et m'a désigné Prophète.",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/2280.mp3" },
  "3:49": { surah: "آل عمران", frName: "Âl ʿImrān", ayah: 49,
    ar: "وَرَسُولًا إِلَىٰ بَنِي إِسْرَائِيلَ أَنِّي قَدْ جِئْتُكُمْ بِآيَةٍ مِنْ رَبِّكُمْ ۖ أَنِّي أَخْلُقُ لَكُمْ مِنَ الطِّينِ كَهَيْئَةِ الطَّيْرِ فَأَنْفُخُ فِيهِ فَيَكُونُ طَيْرًا بِإِذْنِ اللَّهِ ۖ وَأُبْرِئُ الْأَكْمَهَ وَالْأَبْرَصَ وَأُحْيِي الْمَوْتَىٰ بِإِذْنِ اللَّهِ ۖ وَأُنَبِّئُكُمْ بِمَا تَأْكُلُونَ وَمَا تَدَّخِرُونَ فِي بُيُوتِكُمْ ۚ إِنَّ فِي ذَٰلِكَ لَآيَةً لَكُمْ إِنْ كُنْتُمْ مُؤْمِنِينَ",
    fr: "et Il sera le messager aux enfants d'Israël, [et leur dira] : « En vérité, je viens à vous avec un signe de la part de votre Seigneur. Pour vous, je forme de la glaise comme la figure d'un oiseau, puis je souffle dedans : et, par la permission d'Allah, cela devient un oiseau. Et je guéris l'aveugle-né et le lépreux, et je ressuscite les morts, par la permission d'Allah. Et je vous apprends ce que vous mangez et ce que vous amassez dans vos maisons. Voilà bien là un signe, pour vous, si vous êtes croyants !",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/342.mp3" },
  "3:50": { surah: "آل عمران", frName: "Âl ʿImrān", ayah: 50,
    ar: "وَمُصَدِّقًا لِمَا بَيْنَ يَدَيَّ مِنَ التَّوْرَاةِ وَلِأُحِلَّ لَكُمْ بَعْضَ الَّذِي حُرِّمَ عَلَيْكُمْ ۚ وَجِئْتُكُمْ بِآيَةٍ مِنْ رَبِّكُمْ فَاتَّقُوا اللَّهَ وَأَطِيعُونِ",
    fr: "Et je confirme ce qu'il y a dans la Thora révélée avant moi, et je vous rends licite une partie de ce qui vous était interdit. Et j'ai certes apporté un signe de votre Seigneur. Craignez Allah donc, et obéissez-moi.",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/343.mp3" },
  "3:54": { surah: "آل عمران", frName: "Âl ʿImrān", ayah: 54,
    ar: "وَمَكَرُوا وَمَكَرَ اللَّهُ ۖ وَاللَّهُ خَيْرُ الْمَاكِرِينَ",
    fr: "Et ils [les autres] se mirent à comploter. Allah a fait échouer leur complot. Et c'est Allah qui sait le mieux leur machination !",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/347.mp3" },
  "5:110": { surah: "المائدة", frName: "Al-Mā'ida", ayah: 110,
    ar: "إِذْ قَالَ اللَّهُ يَا عِيسَى ابْنَ مَرْيَمَ اذْكُرْ نِعْمَتِي عَلَيْكَ وَعَلَىٰ وَالِدَتِكَ إِذْ أَيَّدْتُكَ بِرُوحِ الْقُدُسِ تُكَلِّمُ النَّاسَ فِي الْمَهْدِ وَكَهْلًا ۖ وَإِذْ عَلَّمْتُكَ الْكِتَابَ وَالْحِكْمَةَ وَالتَّوْرَاةَ وَالْإِنْجِيلَ ۖ وَإِذْ تَخْلُقُ مِنَ الطِّينِ كَهَيْئَةِ الطَّيْرِ بِإِذْنِي فَتَنْفُخُ فِيهَا فَتَكُونُ طَيْرًا بِإِذْنِي ۖ وَتُبْرِئُ الْأَكْمَهَ وَالْأَبْرَصَ بِإِذْنِي ۖ وَإِذْ تُخْرِجُ الْمَوْتَىٰ بِإِذْنِي ۖ وَإِذْ كَفَفْتُ بَنِي إِسْرَائِيلَ عَنْكَ إِذْ جِئْتَهُمْ بِالْبَيِّنَاتِ فَقَالَ الَّذِينَ كَفَرُوا مِنْهُمْ إِنْ هَٰذَا إِلَّا سِحْرٌ مُبِينٌ",
    fr: "Et quand Allah dira : « O Jésus, fils de Marie, rappelle-toi Mon bienfait sur toi et sur ta mère quand Je te fortifiais du Saint-Esprit. Au berceau tu parlais aux gens, tout comme en ton âge mûr. Je t'enseignais le Livre, la Sagesse, la Thora et l'Evangile ! Tu fabriquais de l'argile comme une forme d'oiseau par Ma permission ; puis tu soufflais dedans. Alors par Ma permission, elle devenait oiseau. Et tu guérissais par Ma permission, l'aveugle-né et le lépreux. Et par Ma permission, tu faisais revivre les morts. Je te protégeais contre les Enfants d'Israël pendant que tu leur apportais les preuves. Mais ceux d'entre eux qui ne croyaient pas dirent : « Ceci n'est que de la magie évidente ».",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/779.mp3" },
  "61:6": { surah: "الصف", frName: "As-Saff", ayah: 6,
    ar: "وَإِذْ قَالَ عِيسَى ابْنُ مَرْيَمَ يَا بَنِي إِسْرَائِيلَ إِنِّي رَسُولُ اللَّهِ إِلَيْكُمْ مُصَدِّقًا لِمَا بَيْنَ يَدَيَّ مِنَ التَّوْرَاةِ وَمُبَشِّرًا بِرَسُولٍ يَأْتِي مِنْ بَعْدِي اسْمُهُ أَحْمَدُ ۖ فَلَمَّا جَاءَهُمْ بِالْبَيِّنَاتِ قَالُوا هَٰذَا سِحْرٌ مُبِينٌ",
    fr: "Et quand Jésus fils de Marie dit : « O Enfants d'Israël, je suis vraiment le Messager d'Allah [envoyé] à vous, confirmateur de ce qui, dans la Thora, est antérieur à moi, et annonciateur d'un Messager à venir après moi, dont le nom sera « Ahmad ». Puis quand celui-ci vint à eux avec des preuves évidentes, ils dirent : « C'est là une magie manifeste ».",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/5169.mp3" },
  "5:114": { surah: "المائدة", frName: "Al-Mā'ida", ayah: 114,
    ar: "قَالَ عِيسَى ابْنُ مَرْيَمَ اللَّهُمَّ رَبَّنَا أَنْزِلْ عَلَيْنَا مَائِدَةً مِنَ السَّمَاءِ تَكُونُ لَنَا عِيدًا لِأَوَّلِنَا وَآخِرِنَا وَآيَةً مِنْكَ ۖ وَارْزُقْنَا وَأَنْتَ خَيْرُ الرَّازِقِينَ",
    fr: "« O Allah, notre Seigneur, dit Jésus, fils de Marie, fais descendre du ciel sur nous une table servie qui soit une fête pour nous, pour le premier d'entre nous, comme pour le dernier, ainsi qu'un signe de Ta part. Nourris-nous : Tu es le meilleur des nourrisseurs. »",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/783.mp3" },
  "4:157": { surah: "النساء", frName: "An-Nisā'", ayah: 157,
    ar: "وَقَوْلِهِمْ إِنَّا قَتَلْنَا الْمَسِيحَ عِيسَى ابْنَ مَرْيَمَ رَسُولَ اللَّهِ وَمَا قَتَلُوهُ وَمَا صَلَبُوهُ وَلَٰكِنْ شُبِّهَ لَهُمْ ۚ وَإِنَّ الَّذِينَ اخْتَلَفُوا فِيهِ لَفِي شَكٍّ مِنْهُ ۚ مَا لَهُمْ بِهِ مِنْ عِلْمٍ إِلَّا اتِّبَاعَ الظَّنِّ ۚ وَمَا قَتَلُوهُ يَقِينًا",
    fr: "et à cause de leur parole : « Nous avons vraiment tué le Christ, Jésus, fils de Marie, le Messager d'Allah »… Or, ils ne l'ont ni tué ni crucifié ; mais ce n'était qu'un faux semblant ! Et ceux qui ont discuté sur son sujet sont vraiment dans l'incertitude : ils n'en ont aucune connaissance certaine, ils ne font que suivre des conjectures ; et ils ne l'ont certainement pas tué.",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/650.mp3" },
  "4:158": { surah: "النساء", frName: "An-Nisā'", ayah: 158,
    ar: "بَلْ رَفَعَهُ اللَّهُ إِلَيْهِ ۚ وَكَانَ اللَّهُ عَزِيزًا حَكِيمًا",
    fr: "mais Allah l'a élevé vers Lui. Et Allah est Puissant et Sage.",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/651.mp3" },
  "43:59": { surah: "الزخرف", frName: "Az-Zukhruf", ayah: 59,
    ar: "إِنْ هُوَ إِلَّا عَبْدٌ أَنْعَمْنَا عَلَيْهِ وَجَعَلْنَاهُ مَثَلًا لِبَنِي إِسْرَائِيلَ",
    fr: "Il (Jésus) n'était qu'un Serviteur que Nous avions comblé de bienfaits et que Nous avions désigné en exemple aux Enfants d'Israël.",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/4384.mp3" },

  /* --- Sourat Yūsuf (12) --- */
  "12:4": { surah: "يوسف", frName: "Yūsuf", ayah: 4,
    ar: "إِذْ قَالَ يُوسُفُ لِأَبِيهِ يَا أَبَتِ إِنِّي رَأَيْتُ أَحَدَ عَشَرَ كَوْكَبًا وَالشَّمْسَ وَالْقَمَرَ رَأَيْتُهُمْ لِي سَاجِدِينَ",
    fr: "Quand Joseph dit à son père : « O mon père, j'ai vu [en songe], onze étoiles, et aussi le soleil et la lune ; je les ai vus prosternés devant moi ».",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1600.mp3" },
  "12:5": { surah: "يوسف", frName: "Yūsuf", ayah: 5,
    ar: "قَالَ يَا بُنَيَّ لَا تَقْصُصْ رُؤْيَاكَ عَلَىٰ إِخْوَتِكَ فَيَكِيدُوا لَكَ كَيْدًا ۖ إِنَّ الشَّيْطَانَ لِلْإِنْسَانِ عَدُوٌّ مُبِينٌ",
    fr: "« O mon fils, dit-il, ne raconte pas ta vision à tes frères car ils monteraient un complot contre toi ; le Diable est certainement pour l'homme un ennemi déclaré.",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1601.mp3" },
  "12:15": { surah: "يوسف", frName: "Yūsuf", ayah: 15,
    ar: "فَلَمَّا ذَهَبُوا بِهِ وَأَجْمَعُوا أَنْ يَجْعَلُوهُ فِي غَيَابَتِ الْجُبِّ ۚ وَأَوْحَيْنَا إِلَيْهِ لَتُنَبِّئَنَّهُمْ بِأَمْرِهِمْ هَٰذَا وَهُمْ لَا يَشْعُرُونَ",
    fr: "Et lorsqu'ils l'eurent emmené, et se furent mis d'accord pour le jeter dans les profondeurs invisibles du puits, Nous lui révélâmes : « Tu les informeras sûrement de cette affaire sans qu'ils s'en rendent compte ».",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1611.mp3" },
  "12:18": { surah: "يوسف", frName: "Yūsuf", ayah: 18,
    ar: "وَجَاءُوا عَلَىٰ قَمِيصِهِ بِدَمٍ كَذِبٍ ۚ قَالَ بَلْ سَوَّلَتْ لَكُمْ أَنْفُسُكُمْ أَمْرًا ۖ فَصَبْرٌ جَمِيلٌ ۖ وَاللَّهُ الْمُسْتَعَانُ عَلَىٰ مَا تَصِفُونَ",
    fr: "Ils apportèrent sa tunique tachée d'un faux sang. Il dit : « Vos âmes, plutôt, vous ont suggéré quelque chose… [Il ne me reste plus donc] qu'une belle patience ! C'est Allah qu'il faut appeler au secours contre ce que vous racontez ! »",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1614.mp3" },
  "12:19": { surah: "يوسف", frName: "Yūsuf", ayah: 19,
    ar: "وَجَاءَتْ سَيَّارَةٌ فَأَرْسَلُوا وَارِدَهُمْ فَأَدْلَىٰ دَلْوَهُ ۖ قَالَ يَا بُشْرَىٰ هَٰذَا غُلَامٌ ۚ وَأَسَرُّوهُ بِضَاعَةً ۚ وَاللَّهُ عَلِيمٌ بِمَا يَعْمَلُونَ",
    fr: "Or, vint une caravane. Ils envoyèrent leur chercheur d'eau, qui fit descendre son seau. Il dit : « Bonne nouvelle ! Voilà un garçon ! » Et ils le dissimulèrent [pour le vendre] telle une marchandise. Allah cependant savait fort bien ce qu'ils faisaient.",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1615.mp3" },
  "12:21": { surah: "يوسف", frName: "Yūsuf", ayah: 21,
    ar: "وَقَالَ الَّذِي اشْتَرَاهُ مِنْ مِصْرَ لِامْرَأَتِهِ أَكْرِمِي مَثْوَاهُ عَسَىٰ أَنْ يَنْفَعَنَا أَوْ نَتَّخِذَهُ وَلَدًا ۚ وَكَذَٰلِكَ مَكَّنَّا لِيُوسُفَ فِي الْأَرْضِ وَلِنُعَلِّمَهُ مِنْ تَأْوِيلِ الْأَحَادِيثِ ۚ وَاللَّهُ غَالِبٌ عَلَىٰ أَمْرِهِ وَلَٰكِنَّ أَكْثَرَ النَّاسِ لَا يَعْلَمُونَ",
    fr: "Et celui qui l'acheta était de l'Égypte. Il dit à sa femme : « Accorde-lui une généreuse hospitalité. Il se peut qu'il nous soit utile ou que nous l'adoptions comme notre enfant. » Ainsi avons-Nous raffermi Joseph dans le pays et nous lui avons appris l'interprétation des rêves. Et Allah est souverain en Son Commandement : mais la plupart des gens ne savent pas.",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1617.mp3" },
  "12:23": { surah: "يوسف", frName: "Yūsuf", ayah: 23,
    ar: "وَرَاوَدَتْهُ الَّتِي هُوَ فِي بَيْتِهَا عَنْ نَفْسِهِ وَغَلَّقَتِ الْأَبْوَابَ وَقَالَتْ هَيْتَ لَكَ ۚ قَالَ مَعَاذَ اللَّهِ ۖ إِنَّهُ رَبِّي أَحْسَنَ مَثْوَايَ ۖ إِنَّهُ لَا يُفْلِحُ الظَّالِمُونَ",
    fr: "Or celle [Zulikha] qui l'avait reçu dans sa maison essaya de le séduire. Et elle ferma bien les portes et dit : « Viens, (je suis prête pour toi !) » — Il dit : « Qu'Allah me protège ! C'est mon maître qui m'a accordé un bon asile. Vraiment les injustes ne réussissent pas ».",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1619.mp3" },
  "12:25": { surah: "يوسف", frName: "Yūsuf", ayah: 25,
    ar: "وَاسْتَبَقَا الْبَابَ وَقَدَّتْ قَمِيصَهُ مِنْ دُبُرٍ وَأَلْفَيَا سَيِّدَهَا لَدَى الْبَابِ ۚ قَالَتْ مَا جَزَاءُ مَنْ أَرَادَ بِأَهْلِكَ سُوءًا إِلَّا أَنْ يُسْجَنَ أَوْ عَذَابٌ أَلِيمٌ",
    fr: "Et tous deux coururent vers la porte, et elle lui déchira sa tunique par derrière. Ils trouvèrent le mari [de cette femme] à la porte. Elle dit : « Quelle serait la punition de quiconque a voulu faire du mal à ta famille, sinon la prison, ou un châtiment douloureux ? »",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1621.mp3" },
  "12:31": { surah: "يوسف", frName: "Yūsuf", ayah: 31,
    ar: "فَلَمَّا سَمِعَتْ بِمَكْرِهِنَّ أَرْسَلَتْ إِلَيْهِنَّ وَأَعْتَدَتْ لَهُنَّ مُتَّكَأً وَآتَتْ كُلَّ وَاحِدَةٍ مِنْهُنَّ سِكِّينًا وَقَالَتِ اخْرُجْ عَلَيْهِنَّ ۖ فَلَمَّا رَأَيْنَهُ أَكْبَرْنَهُ وَقَطَّعْنَ أَيْدِيَهُنَّ وَقُلْنَ حَاشَ لِلَّهِ مَا هَٰذَا بَشَرًا إِنْ هَٰذَا إِلَّا مَلَكٌ كَرِيمٌ",
    fr: "Lorsqu'elle eut entendu leur fourberie, elle leur envoya [des invitations,] et prépara pour elles une collation ; et elle remit à chacune d'elles un couteau. Puis elle dit : « Sors devant elles, (Joseph !) » — Lorsqu'elles le virent, elles l'admirèrent, se coupèrent les mains et dirent : « À Allah ne plaise ! Ce n'est pas un être humain, ce n'est qu'un ange noble ! »",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1627.mp3" },
  "12:33": { surah: "يوسف", frName: "Yūsuf", ayah: 33,
    ar: "قَالَ رَبِّ السِّجْنُ أَحَبُّ إِلَيَّ مِمَّا يَدْعُونَنِي إِلَيْهِ ۖ وَإِلَّا تَصْرِفْ عَنِّي كَيْدَهُنَّ أَصْبُ إِلَيْهِنَّ وَأَكُنْ مِنَ الْجَاهِلِينَ",
    fr: "Il dit : « O mon Seigneur, la prison m'est préférable à ce à quoi elles m'invitent. Et si Tu n'écartes pas de moi leur ruse, je pencherai vers elles et serai du nombre des ignorants » [des pécheurs].",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1629.mp3" },
  "12:36": { surah: "يوسف", frName: "Yūsuf", ayah: 36,
    ar: "وَدَخَلَ مَعَهُ السِّجْنَ فَتَيَانِ ۖ قَالَ أَحَدُهُمَا إِنِّي أَرَانِي أَعْصِرُ خَمْرًا ۖ وَقَالَ الْآخَرُ إِنِّي أَرَانِي أَحْمِلُ فَوْقَ رَأْسِي خُبْزًا تَأْكُلُ الطَّيْرُ مِنْهُ ۖ نَبِّئْنَا بِتَأْوِيلِهِ ۖ إِنَّا نَرَاكَ مِنَ الْمُحْسِنِينَ",
    fr: "Deux valets entrèrent avec lui en prison. L'un d'eux dit : « Je me voyais [en rêve] pressant du raisin… » Et l'autre dit : « Et moi, je me voyais portant sur ma tête du pain dont les oiseaux mangeaient. Apprends-nous l'interprétation (de nos rêves), nous te voyons au nombre des bienfaisants ».",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1632.mp3" },
  "12:41": { surah: "يوسف", frName: "Yūsuf", ayah: 41,
    ar: "يَا صَاحِبَيِ السِّجْنِ أَمَّا أَحَدُكُمَا فَيَسْقِي رَبَّهُ خَمْرًا ۖ وَأَمَّا الْآخَرُ فَيُصْلَبُ فَتَأْكُلُ الطَّيْرُ مِنْ رَأْسِهِ ۚ قُضِيَ الْأَمْرُ الَّذِي فِيهِ تَسْتَفْتِيَانِ",
    fr: "O mes deux compagnons de prison ! L'un de vous donnera du vin à boire à son maître ; quant à l'autre, il sera crucifié, et les oiseaux mangeront de sa tête. L'affaire sur laquelle vous me consultez est déjà décidée. »",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1637.mp3" },
  "12:43": { surah: "يوسف", frName: "Yūsuf", ayah: 43,
    ar: "وَقَالَ الْمَلِكُ إِنِّي أَرَىٰ سَبْعَ بَقَرَاتٍ سِمَانٍ يَأْكُلُهُنَّ سَبْعٌ عِجَافٌ وَسَبْعَ سُنْبُلَاتٍ خُضْرٍ وَأُخَرَ يَابِسَاتٍ ۖ يَا أَيُّهَا الْمَلَأُ أَفْتُونِي فِي رُؤْيَايَ إِنْ كُنْتُمْ لِلرُّؤْيَا تَعْبُرُونَ",
    fr: "Et le roi dit : « En vérité, je voyais (en rêve) sept vaches grasses mangées par sept maigres ; et sept épis verts, et autant d'autres, secs. O conseil de notables, donnez-moi une explication de ma vision, si vous savez interpréter le rêve ».",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1639.mp3" },
  "12:47": { surah: "يوسف", frName: "Yūsuf", ayah: 47,
    ar: "قَالَ تَزْرَعُونَ سَبْعَ سِنِينَ دَأَبًا فَمَا حَصَدْتُمْ فَذَرُوهُ فِي سُنْبُلِهِ إِلَّا قَلِيلًا مِمَّا تَأْكُلُونَ",
    fr: "Alors [Joseph dit] : « Vous sèmerez pendant sept années consécutives. Tout ce que vous aurez moissonné, laissez-le en épi, sauf le peu que vous consommerez.",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1643.mp3" },
  "12:55": { surah: "يوسف", frName: "Yūsuf", ayah: 55,
    ar: "قَالَ اجْعَلْنِي عَلَىٰ خَزَائِنِ الْأَرْضِ ۖ إِنِّي حَفِيظٌ عَلِيمٌ",
    fr: "Et [Joseph] dit : « Assigne-moi les dépôts du territoire : je suis bon gardien et connaisseur ».",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1651.mp3" },
  "12:58": { surah: "يوسف", frName: "Yūsuf", ayah: 58,
    ar: "وَجَاءَ إِخْوَةُ يُوسُفَ فَدَخَلُوا عَلَيْهِ فَعَرَفَهُمْ وَهُمْ لَهُ مُنْكِرُونَ",
    fr: "Et les frères de Joseph vinrent et entrèrent auprès de lui. Il les reconnut, mais eux ne le reconnurent pas.",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1654.mp3" },
  "12:70": { surah: "يوسف", frName: "Yūsuf", ayah: 70,
    ar: "فَلَمَّا جَهَّزَهُمْ بِجَهَازِهِمْ جَعَلَ السِّقَايَةَ فِي رَحْلِ أَخِيهِ ثُمَّ أَذَّنَ مُؤَذِّنٌ أَيَّتُهَا الْعِيرُ إِنَّكُمْ لَسَارِقُونَ",
    fr: "Puis, quand il leur eut fourni leurs provisions, il mit la coupe dans le sac de son frère. Ensuite un crieur annonça : « Caravaniers ! vous êtes des voleurs ».",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1666.mp3" },
  "12:83": { surah: "يوسف", frName: "Yūsuf", ayah: 83,
    ar: "قَالَ بَلْ سَوَّلَتْ لَكُمْ أَنْفُسُكُمْ أَمْرًا ۖ فَصَبْرٌ جَمِيلٌ ۖ عَسَى اللَّهُ أَنْ يَأْتِيَنِي بِهِمْ جَمِيعًا ۚ إِنَّهُ هُوَ الْعَلِيمُ الْحَكِيمُ",
    fr: "Alors [Jacob] dit : Vos âmes plutôt vous ont inspiré [d'entreprendre] quelque chose !… Oh ! belle patience. Il se peut qu'Allah me les ramènera tous les deux. Car c'est Lui l'Omniscient, le Sage ».",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1679.mp3" },
  "12:87": { surah: "يوسف", frName: "Yūsuf", ayah: 87,
    ar: "يَا بَنِيَّ اذْهَبُوا فَتَحَسَّسُوا مِنْ يُوسُفَ وَأَخِيهِ وَلَا تَيْأَسُوا مِنْ رَوْحِ اللَّهِ ۖ إِنَّهُ لَا يَيْأَسُ مِنْ رَوْحِ اللَّهِ إِلَّا الْقَوْمُ الْكَافِرُونَ",
    fr: "O mes fils ! Partez et enquérez-vous de Joseph et de son frère. Et ne désespérez pas de la miséricorde d'Allah. Ce sont seulement les gens mécréants qui désespèrent de la miséricorde d'Allah ».",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1683.mp3" },
  "12:93": { surah: "يوسف", frName: "Yūsuf", ayah: 93,
    ar: "اذْهَبُوا بِقَمِيصِي هَٰذَا فَأَلْقُوهُ عَلَىٰ وَجْهِ أَبِي يَأْتِ بَصِيرًا وَأْتُونِي بِأَهْلِكُمْ أَجْمَعِينَ",
    fr: "Emportez ma tunique que voici, et appliquez-la sur le visage de mon père : il recouvrera [aussitôt] la vue. Et amenez-moi toute votre famille ».",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1689.mp3" },
  "12:100": { surah: "يوسف", frName: "Yūsuf", ayah: 100,
    ar: "وَرَفَعَ أَبَوَيْهِ عَلَى الْعَرْشِ وَخَرُّوا لَهُ سُجَّدًا ۖ وَقَالَ يَا أَبَتِ هَٰذَا تَأْوِيلُ رُؤْيَايَ مِنْ قَبْلُ قَدْ جَعَلَهَا رَبِّي حَقًّا ۖ وَقَدْ أَحْسَنَ بِي إِذْ أَخْرَجَنِي مِنَ السِّجْنِ وَجَاءَ بِكُمْ مِنَ الْبَدْوِ مِنْ بَعْدِ أَنْ نَزَغَ الشَّيْطَانُ بَيْنِي وَبَيْنَ إِخْوَتِي ۚ إِنَّ رَبِّي لَطِيفٌ لِمَا يَشَاءُ ۚ إِنَّهُ هُوَ الْعَلِيمُ الْحَكِيمُ",
    fr: "Et il éleva ses parents sur le trône, et tous tombèrent devant lui, prosternés. Et il dit : « O mon père, voilà l'interprétation de mon rêve de jadis. Allah l'a bel et bien réalisé… Et Il m'a certainement fait du bien quand Il m'a fait sortir de prison et qu'Il vous a fait venir de la campagne, [du désert], après que le Diable ait suscité la discorde entre mes frères et moi. Mon Seigneur est plein de douceur pour ce qu'Il veut. Et c'est Lui l'Omniscient, le Sage.",
    audio: "https://cdn.islamic.network/quran/audio/128/ar.alafasy/1696.mp3" },
};
